exports.trad = {
	"ability": [
		{"en": "adaptability", "es": "adaptable"},
		{"en": "aerilate", "es": "Piel Celeste"},
		{"en": "aftermath", "es": "Resquicio"},
		{"en": "air lock", "es": "Bucle aire"},
		{"en": "analytic", "es": "Cálculo final"},
		{"en": "anger point", "es": "Irascible"},
		{"en": "anticipation", "es": "Anticipación"},
		{"en": "arena trap", "es": "Trampa arena"},
		{"en": "aroma veil", "es": "Velo aroma"},
		{"en": "aura break", "es": "Rompeaura"},
		{"en": "bad dreams", "es": "Mal sueño"},
		{"en": "battle armor", "es": "Armadura batalla"},
		{"en": "big pecks", "es": "Sacapecho"},
		{"en": "blaze", "es": "Mar llamas"},
		{"en": "bulletproof", "es": "Antibalas"},
		{"en": "cheek pouch", "es": "Carrillo"},
		{"en": "chlorophyll", "es": "Clorofila"},
		{"en": "clear body", "es": "Cuerpo puro"},
		{"en": "cloud nine", "es": "Aclimatación"},
		{"en": "color change", "es": "Cambio color"},
		{"en": "competitive", "es": "Tenacidad"},
		{"en": "compoundeyes", "es": "Ojocompuesto"},
		{"en": "contrary", "es": "Respondón"},
		{"en": "cursed body", "es": "Cuerpo maldito"},
		{"en": "cute charm", "es": "Gran encanto"},
		{"en": "damp", "es": "Humedad"},
		{"en": "dark aura", "es": "Aura oscura"},
		{"en": "defeatist", "es": "Flaqueza"},
		{"en": "defiant", "es": "Competitivo"},
		{"en": "delta stream", "es": "Ráfaga delta"},
		{"en": "desolate land", "es": "Tierra del ocaso"},
		{"en": "download", "es": "Descarga"},
		{"en": "drizzle", "es": "Llovizna"},
		{"en": "drought", "es": "Sequía"},
		{"en": "dry skin", "es": "Piel seca"},
		{"en": "early bird", "es": "Madrugar"},
		{"en": "effect spore", "es": "Efecto espora"},
		{"en": "fairy aura", "es": "Aura feérica"},
		{"en": "filter", "es": "Fitro"},
		{"en": "flame body", "es": "Cuerpo llama"},
		{"en": "flare boost", "es": "Ímpetu ardiente"},
		{"en": "flash fire", "es": "Absorbe fuego"},
		{"en": "flower gift", "es": "Don floral"},
		{"en": "flower veil", "es": "Velo flor"},
		{"en": "forecast", "es": "Predicción"},
		{"en": "forewarn", "es": "Alerta"},
		{"en": "friend guard", "es": "Compiescolta"},
		{"en": "frisk", "es": "Cacheo"},
		{"en": "fur coat", "es": "Pelaje recio"},
		{"en": "gale wings", "es": "Alas vendaval"},
		{"en": "gluttony", "es": "Gula"},
		{"en": "gooey", "es": "Baba"},
		{"en": "grass pelt", "es": "Manto frondoso"},
		{"en": "guts", "es": "Agallas"},
		{"en": "harvest", "es": "Cosecha"},
		{"en": "healer", "es": "Alma cura"},
		{"en": "heatproof", "es": "Ignífugo"},
		{"en": "heavy metal", "es": "Metal pesado"},
		{"en": "honey gather", "es": "Recogemiel"},
		{"en": "huge power", "es": "Potencia"},
		{"en": "hustle", "es": "Entusiasmo"},
		{"en": "hydration", "es": "Hidratación"},
		{"en": "hyper cutter", "es": "Corte fuerte"},
		{"en": "ice body", "es": "Gélido"},
		{"en": "illuminate", "es": "Iluminación"},
		{"en": "illusion", "es": "Ilusión"},
		{"en": "immunity", "es": "Inmunidad"},
		{"en": "imposter", "es": "Impostor"},
		{"en": "infiltrator", "es": "Allanamiento"},
		{"en": "inner focus", "es": "Foco interno"},
		{"en": "insomnia", "es": "Insomnio"},
		{"en": "intimidate", "es": "Intimidación"},
		{"en": "iron barbs", "es": "Punta acero"},
		{"en": "iron fist", "es": "Puño férreo"},
		{"en": "justified", "es": "Justiciero"},
		{"en": "keen eye", "es": "Vista Lince"},
		{"en": "klutz", "es": "Zoquete"},
		{"en": "leaf guard", "es": "Defensa hoja"},
		{"en": "levitate", "es": "Levitación"},
		{"en": "light metal", "es": "Metal liviano"},
		{"en": "lightningrod", "es": "Pararrayos"},
		{"en": "limber", "es": "Flexibilidad"},
		{"en": "liquid ooze", "es": "Lodo líquido"},
		{"en": "magic bounce", "es": "Esoejo mágico"},
		{"en": "magic guard", "es": "Muro mágico"},
		{"en": "magician", "es": "Prestidigitador"},
		{"en": "magma armor", "es": "Escudo magma"},
		{"en": "magnet pull", "es": "Imán"},
		{"en": "marvel scale", "es": "Escama especial"},
		{"en": "mega launcher", "es": "Megadisparador"},
		{"en": "minus", "es": "Menos"},
		{"en": "mold breaker", "es": "Rompemoldes"},
		{"en": "moody", "es": "Veleta"},
		{"en": "motor drive", "es": "Electromotor"},
		{"en": "moxie", "es": "Autoestima"},
		{"en": "multiscale", "es": "Compensación"},
		{"en": "multitype", "es": "Multitipo"},
		{"en": "mummy", "es": "Momia"},
		{"en": "natural cure", "es": "alternacura"},
		{"en": "no guard", "es": "nullodifesa"},
		{"en": "normalize", "es": "normalità"},
		{"en": "oblivious", "es": "indifferenza"},
		{"en": "overcoat", "es": "copricapo"},
		{"en": "overgrow", "es": "erbaiuto"},
		{"en": "own tempo", "es": "mente locale"},
		{"en": "parental bond", "es": "amorefiliale"},
		{"en": "pickpocket", "es": "arraffalesto"},
		{"en": "pickup", "es": "raccolta"},
		{"en": "plus", "es": "più"},
		{"en": "pixilate", "es": "pellefolletto"},
		{"en": "poison heal", "es": "velencura"},
		{"en": "poison point", "es": "velenopunto"},
		{"en": "poison touch", "es": "velentocco"},
		{"en": "prankster", "es": "burla"},
		{"en": "pressure", "es": "pressione"},
		{"en": "primordial sea", "es": "mare primordiale"},
		{"en": "protean", "es": "mutatipo"},
		{"en": "pure power", "es": "forzapura"},
		{"en": "quick feet", "es": "piedisvelti"},
		{"en": "rain dish", "es": "copripioggia"},
		{"en": "rattled", "es": "paura"},
		{"en": "reckless", "es": "temerarietà"},
		{"en": "refrigerate", "es": "pellegelo"},
		{"en": "regenerator", "es": "rigenergia"},
		{"en": "rivalry", "es": "antagonismo"},
		{"en": "rock head", "es": "testadura"},
		{"en": "rough skin", "es": "cartavetro"},
		{"en": "run away", "es": "fugafacile"},
		{"en": "sand force", "es": "silicoforza"},
		{"en": "sand rush", "es": "remasabbia"},
		{"en": "sand stream", "es": "sabbia fiume"},
		{"en": "sand veil", "es": "sabbiavelo"},
		{"en": "sap sipper", "es": "mangiaerba"},
		{"en": "scrappy", "es": "nervisaldi"},
		{"en": "serene grace", "es": "leggiadro"},
		{"en": "shadow tag", "es": "pedinombra"},
		{"en": "shed skin", "es": "muta"},
		{"en": "sheer force", "es": "forzabruta"},
		{"en": "shell armor", "es": "guscioscudo"},
		{"en": "shield dust", "es": "polvoscudo"},
		{"en": "simple", "es": "disinvoltura"},
		{"en": "skill link", "es": "abillegame"},
		{"en": "slow start", "es": "lentoinizio"},
		{"en": "sniper", "es": "cecchino"},
		{"en": "snow cloak", "es": "mantelneve"},
		{"en": "snow warning", "es": "scendineve"},
		{"en": "solar power", "es": "solarpotere"},
		{"en": "solid rock", "es": "solidroccia"},
		{"en": "soundproof", "es": "antisuono"},
		{"en": "speed boost", "es": "acceleratore"},
		{"en": "stall", "es": "rallentatore"},
		{"en": "stance change", "es": "accendilotta"},
		{"en": "static", "es": "statico"},
		{"en": "steadfast", "es": "cuordeciso"},
		{"en": "stench", "es": "tanfo"},
		{"en": "sticky hold", "es": "antifurto"},
		{"en": "storm drain", "es": "acquascolo"},
		{"en": "strong jaw", "es": "ferromascella"},
		{"en": "sturdy", "es": "vigore"},
		{"en": "suction cups", "es": "ventose"},
		{"en": "super luck", "es": "supersorte"},
		{"en": "swarm", "es": "aiutinsetto"},
		{"en": "sweet veil", "es": "dolcevelo"},
		{"en": "swift swim", "es": "nuotovelox"},
		{"en": "symbiosis", "es": "simbiosi"},
		{"en": "synchronize", "es": "sincronismo"},
		{"en": "tangled feet", "es": "intricopiedi"},
		{"en": "technician", "es": "tecnico"},
		{"en": "telepathy", "es": "telepatia"},
		{"en": "teravolt", "es": "teravolt"},
		{"en": "thick fat", "es": "grassospesso"},
		{"en": "tinted lens", "es": "lentifumé"},
		{"en": "torrent", "es": "acquaiuto"},
		{"en": "tough claws", "es": "unghiedure"},
		{"en": "toxic boost", "es": "velenimpeto"},
		{"en": "trace", "es": "traccia"},
		{"en": "truant", "es": "pigrizia"},
		{"en": "turboblaze", "es": "piroturbina"},
		{"en": "unaware", "es": "imprudenza"},
		{"en": "unburden", "es": "agiltecnica"},
		{"en": "unnerve", "es": "agitazione"},
		{"en": "victory star", "es": "tinovictoria"},
		{"en": "vital spirit", "es": "spiritovivo"},
		{"en": "volt absorb", "es": "assorbivolt"},
		{"en": "water absorb", "es": "assorbiacqua"},
		{"en": "water veil", "es": "idrovelo"},
		{"en": "weak armor", "es": "sottilguscio"},
		{"en": "white smoke", "es": "fumochiaro"},
		{"en": "wonder guard", "es": "magidifesa"},
		{"en": "wonder skin", "es": "splendicute"},
		{"en": "zen mode", "es": "stato zen"}
	],
	"move": [
		{"en": "Close Combat", "es": "A bocajarro"},
		{"en": "Defend Order", "es": "A defender"},
		{"en": "Worry Seed", "es": "Abatidoras"},
		{"en": "Absorb", "es": "Absorber"},
		{"en": "Acid", "es": "Ácido"},
		{"en": "Infestation", "es": "Acoso"},
		{"en": "Acrobatics", "es": "Acróbata"},
		{"en": "Aqua Ring", "es": "Acua aro"},
		{"en": "Aqua Tail", "es": "Acua cola"},
		{"en": "Aqua Jet", "es": "Acua jet"},
		{"en": "Acupressure", "es": "Acupresión"},
		{"en": "Nature power", "es": "Adaptación"},
		{"en": "Aeroblast", "es": "Aerochorro"},
		{"en": "Hone Claws", "es": "Afilagarras"},
		{"en": "Sharpen", "es": "Afilar"},
		{"en": "Vice Grip", "es": "Agarre"},
		{"en": "Crush Grip", "es": "Agarrón"},
		{"en": "Agility", "es": "Agilidad"},
		{"en": "Muddy water", "es": "Agua lodosa"},
		{"en": "Endure", "es": "Aguante"},
		{"en": "Fell Stinger", "es": "Aguijón letal"},
		{"en": "Air cutter", "es": "Aire afilado"},
		{"en": "Attack Order", "es": "Al ataque"},
		{"en": "Steel wing", "es": "Ala de acero"},
		{"en": "Oblivion Wing", "es": "Ala mortífera"},
		{"en": "Snarl", "es": "Alarido"},
		{"en": "Uproar", "es": "Alboroto"},
		{"en": "Autotomize", "es": "Aligerar"},
		{"en": "Refresh", "es": "Alivio"},
		{"en": "Avalanche", "es": "Alud"},
		{"en": "Feint", "es": "Amago"},
		{"en": "Amnesia", "es": "Amnesia"},
		{"en": "Soft-boiled", "es": "Amortiguador"},
		{"en": "Soak", "es": "Anegar"},
		{"en": "Blast burn", "es": "Anillo ígneo"},
		{"en": "Smack Down", "es": "Antiaéreo"},
		{"en": "Quick Guard", "es": "Anticipo"},
		{"en": "Heal Block", "es": "Anticura"},
		{"en": "Covet", "es": "Antojo"},
		{"en": "Disable", "es": "Anulación"},
		{"en": "Scratch", "es": "Arañazo"},
		{"en": "Head Charge", "es": "Ariete"},
		{"en": "Acid armor", "es": "Armadura ácida"},
		{"en": "Aromatherapy", "es": "Aromaterapia"},
		{"en": "Ingrain", "es": "Arraigo"},
		{"en": "Heart Stamp", "es": "Arrumaco"},
		{"en": "Trump Card", "es": "As oculto"},
		{"en": "Dragon Ascent", "es": "Ascenso draco"},
		{"en": "Ember", "es": "Ascuas"},
		{"en": "Horn Leech", "es": "Asta drenaje"},
		{"en": "Bind", "es": "Atadura"},
		{"en": "Sky attack", "es": "Ataque aéreo"},
		{"en": "Wing attack", "es": "Ataque ala"},
		{"en": "Sand Attack", "es": "Ataque arena"},
		{"en": "Bolt Strike", "es": "Ataque fulgor"},
		{"en": "Fury attack", "es": "Ataque furia"},
		{"en": "Bone rush", "es": "Ataque óseo"},
		{"en": "Quick attack", "es": "Ataque rápido"},
		{"en": "Slam", "es": "Atizar"},
		{"en": "Attract", "es": "Atracción"},
		{"en": "Howl", "es": "Aullido"},
		{"en": "Magnetic Flux", "es": "Aura magnética"},
		{"en": "Self-destruct", "es": "Autodestrucción"},
		{"en": "Heal Order", "es": "Auxilio"},
		{"en": "Rock slide", "es": "Avalancha"},
		{"en": "Work Up", "es": "Avivar"},
		{"en": "Assist", "es": "Ayuda"},
		{"en": "Flail", "es": "Azote"},
		{"en": "Barrier", "es": "Barrera"},
		{"en": "Spiky Shield", "es": "Barrera espinosa"},
		{"en": "Milk drink", "es": "Batido"},
		{"en": "Lovely kiss", "es": "Beso amoroso"},
		{"en": "Draining kiss", "es": "Beso drenaje"},
		{"en": "Sweet kiss", "es": "Beso dulce"},
		{"en": "Gastro Acid", "es": "Bilis"},
		{"en": "Block", "es": "Bloqueo"},
		{"en": "Mud-slap", "es": "Bofetón lodo"},
		{"en": "Ice ball", "es": "Bola hielo"},
		{"en": "Mist ball", "es": "Bola neblina"},
		{"en": "Shadow ball", "es": "Bola sombra"},
		{"en": "Electro Ball", "es": "Bola voltio"},
		{"en": "Acid Spray", "es": "Bomba ácida"},
		{"en": "Mud Bomb", "es": "Bomba fango"},
		{"en": "Seed Bomb", "es": "Bomba germen"},
		{"en": "Egg bomb", "es": "Bomba huevo"},
		{"en": "Searing Shot", "es": "Bomba ígnea"},
		{"en": "Magnet Bomb", "es": "Bomba imán"},
		{"en": "Sludge bomb", "es": "Bomba lodo"},
		{"en": "Sonic Boom", "es": "Bomba sónica"},
		{"en": "Yawn", "es": "Bostezo"},
		{"en": "Bounce", "es": "Bote"},
		{"en": "Needle arm", "es": "Brazo pincho"},
		{"en": "Dark Void", "es": "Brecha negra"},
		{"en": "Dazzling Gleam", "es": "Brillo mágico"},
		{"en": "Dive", "es": "Buceo"},
		{"en": "Sand tomb", "es": "Bucle arena"},
		{"en": "Assurance", "es": "Buena baza"},
		{"en": "Bubble", "es": "Burbuja"},
		{"en": "Iron Head", "es": "Cabeza de hierro"},
		{"en": "Skull bash", "es": "Cabezazo"},
		{"en": "Zen Headbutt", "es": "Cabezazo zen"},
		{"en": "Incinerate", "es": "Calcinación"},
		{"en": "Play Nice", "es": "Camaradería"},
		{"en": "Heart Swap", "es": "Cambia almas"},
		{"en": "Guard Swap", "es": "Cambia defensa"},
		{"en": "Power Swap", "es": "Cambia fuerza"},
		{"en": "Ally Switch", "es": "Cambio banda"},
		{"en": "Shift Gear", "es": "Cambio de marcha"},
		{"en": "Flatter", "es": "Camelo"},
		{"en": "Heal bell", "es": "Campana cura"},
		{"en": "Grassy Terrain", "es": "Campo de hierba"},
		{"en": "Misty Terrain", "es": "Campo de niebla"},
		{"en": "Electric Terrain", "es": "Campo eléctrico"},
		{"en": "Camouflage", "es": "Camuflaje"},
		{"en": "Round", "es": "Canon"},
		{"en": "Sing", "es": "Canto"},
		{"en": "Relic Song", "es": "Canto arcaico"},
		{"en": "Ice Shard", "es": "Canto helado"},
		{"en": "Perish song", "es": "Canto mortal"},
		{"en": "Magic coat", "es": "Capa mágica"},
		{"en": "Scary face", "es": "Cara susto"},
		{"en": "Icicle spear", "es": "Carámbano"},
		{"en": "Play Rough", "es": "Carantoña"},
		{"en": "Charge", "es": "Carga"},
		{"en": "Dragon Rush", "es": "Carga dragón"},
		{"en": "Parabolic Charge", "es": "Carga parábola"},
		{"en": "Venoshock", "es": "Carga tóxica"},
		{"en": "Sky Drop", "es": "Caída libre"},
		{"en": "Waterfall", "es": "Cascada"},
		{"en": "Punishment", "es": "Castigo"},
		{"en": "After You", "es": "Cede paso"},
		{"en": "Celebrate", "es": "Celebración"},
		{"en": "Imprison", "es": "Cerca"},
		{"en": "Fairy Lock", "es": "Cerrojo feérico"},
		{"en": "Chatter", "es": "Cháchara"},
		{"en": "Mud sport", "es": "Chapoteo lodo"},
		{"en": "Screech", "es": "Chirrido"},
		{"en": "Spark", "es": "Chispa"},
		{"en": "Discharge", "es": "Chispazo"},
		{"en": "Steam Eruption", "es": "Chorro de vapor"},
		{"en": "Leech life", "es": "Chupavidas"},
		{"en": "Icicle Crash", "es": "Chuzos"},
		{"en": "Twister", "es": "Ciclón"},
		{"en": "Leaf Tornado", "es": "Ciclón de hojas"},
		{"en": "Spike cannon", "es": "Clavo cañón"},
		{"en": "Hold Back", "es": "Clemencia"},
		{"en": "Reflect Type", "es": "Clonatipo"},
		{"en": "Dragon Tail", "es": "Cola dragón"},
		{"en": "Iron tail", "es": "Cola férrea"},
		{"en": "Poison tail", "es": "Cola veneno"},
		{"en": "Ice Fang", "es": "Colmillo hielo"},
		{"en": "Fire Fang", "es": "Colmillo ígneo"},
		{"en": "Thunder Fang", "es": "Colmillo rayo"},
		{"en": "Poison fang", "es": "Colmillo veneno"},
		{"en": "Dream eater", "es": "Come sueños"},
		{"en": "Draco Meteor", "es": "Cometa draco"},
		{"en": "Razor Shell", "es": "Concha filo"},
		{"en": "Forest's Curse", "es": "Condena silvana"},
		{"en": "Confide", "es": "Confidencia"},
		{"en": "Confusion", "es": "Confusión"},
		{"en": "Lucky Chant", "es": "Conjuro"},
		{"en": "Wrap", "es": "Constricción"},
		{"en": "Swagger", "es": "Contoneo"},
		{"en": "Counter", "es": "Contraataque"},
		{"en": "Conversion", "es": "Conversión"},
		{"en": "Conversion 2", "es": "Conversión 2"},
		{"en": "Copycat", "es": "Copión"},
		{"en": "Horn attack", "es": "Cornada"},
		{"en": "Bulk up", "es": "Corpulencia"},
		{"en": "Cut", "es": "Corte"},
		{"en": "Fury cutter", "es": "Corte furia"},
		{"en": "Spacial Rend", "es": "Corte vacío"},
		{"en": "Ion Deluge", "es": "Cortina plasma"},
		{"en": "Tickle", "es": "Cosquillas"},
		{"en": "Slash", "es": "Cuchillada"},
		{"en": "Heavy Slam", "es": "Cuerpo pesado"},
		{"en": "Quiver Dance", "es": "Danza aleteo"},
		{"en": "Entrainment", "es": "Danza amiga"},
		{"en": "Teeter dance", "es": "Danza caos"},
		{"en": "Dragon dance", "es": "Danza dragón"},
		{"en": "Swords dance", "es": "Danza espada"},
		{"en": "Fiery Dance", "es": "Danza llama"},
		{"en": "Rain dance", "es": "Danza lluvia"},
		{"en": "Lunar Dance", "es": "Danza lunar"},
		{"en": "Petal dance", "es": "Danza pétalo"},
		{"en": "Feather Dance", "es": "Danza pluma"},
		{"en": "Secret power", "es": "Daño secreto"},
		{"en": "Iron defense", "es": "Defensa férrea"},
		{"en": "Flower Shield", "es": "Defensa floral"},
		{"en": "Brick break", "es": "Demolición"},
		{"en": "Take down", "es": "Derribo"},
		{"en": "Knock off", "es": "Desarme"},
		{"en": "Growth", "es": "Desarrollo"},
		{"en": "Rest", "es": "Descanso"},
		{"en": "Rollout", "es": "Desenrollar"},
		{"en": "Wish", "es": "Deseo"},
		{"en": "Healing Wish", "es": "Deseo cura"},
		{"en": "Doom desire", "es": "Deseo oculto"},
		{"en": "Glare", "es": "Deslumbrar"},
		{"en": "Defog", "es": "Despejar"},
		{"en": "Revenge", "es": "Desquite"},
		{"en": "Flash", "es": "Destello"},
		{"en": "Pound", "es": "Destructor"},
		{"en": "Detect", "es": "Detección"},
		{"en": "Pay day", "es": "Día de pago"},
		{"en": "Sunny day", "es": "Día soleado"},
		{"en": "String shot", "es": "Disparo demora"},
		{"en": "Mirror Shot", "es": "Disparo espejo"},
		{"en": "Mud shot", "es": "Disparo lodo"},
		{"en": "Roar Of Time", "es": "Distorsión"},
		{"en": "Pain split", "es": "Divide dolor"},
		{"en": "Twineedle", "es": "Doble ataque"},
		{"en": "Double slap", "es": "Doble bofetón"},
		{"en": "Double team", "es": "Doble equipo"},
		{"en": "Double-edge", "es": "Doble filo"},
		{"en": "Double Hit", "es": "Doble golpe"},
		{"en": "Double kick", "es": "Doble patada"},
		{"en": "Signal beam", "es": "Doble rayo"},
		{"en": "Natural Gift", "es": "Don natural"},
		{"en": "Dragon breath", "es": "Dragoaliento"},
		{"en": "Leech seed", "es": "Drenadoras"},
		{"en": "Sweet scent", "es": "Dulce aroma"},
		{"en": "Metal sound", "es": "Eco metálico"},
		{"en": "Echoed Voice", "es": "Eco voz"},
		{"en": "Electrify", "es": "Electrificación"},
		{"en": "Zap cannon", "es": "Electrocañón"},
		{"en": "Electroweb", "es": "Electrotela"},
		{"en": "Embargo", "es": "Embargo"},
		{"en": "Arm thrust", "es": "Empujón"},
		{"en": "Charm", "es": "Encanto"},
		{"en": "Energy Ball", "es": "Energibola"},
		{"en": "Outrage", "es": "Enfado"},
		{"en": "Coil", "es": "Enrosque"},
		{"en": "Flare Blitz", "es": "Envite ígneo"},
		{"en": "Belch", "es": "Eructo"},
		{"en": "Scald", "es": "Escaldar"},
		{"en": "King's Shield", "es": "Escudo real"},
		{"en": "Mat Block", "es": "Escudo tatami"},
		{"en": "Spit up", "es": "Escupir"},
		{"en": "Aura Sphere", "es": "Esfera aural"},
		{"en": "Endeavor", "es": "Esfuerzo"},
		{"en": "Wake-up Slap", "es": "Espabila"},
		{"en": "Trick Room", "es": "Espacio raro"},
		{"en": "Sacred Sword", "es": "Espada santa"},
		{"en": "Spore", "es": "Espora"},
		{"en": "Cotton spore", "es": "Esporagodón"},
		{"en": "Sketch", "es": "Esquema"},
		{"en": "Eruption", "es": "Estallido"},
		{"en": "Smelling Salts", "es": "Estímulo"},
		{"en": "Struggle Bug", "es": "Estoicismo"},
		{"en": "Boomburst", "es": "Estruendo"},
		{"en": "Wring Out", "es": "Estrujón"},
		{"en": "Dig", "es": "Excavar"},
		{"en": "Explosion", "es": "Explosión"},
		{"en": "False swipe", "es": "Falsotortazo"},
		{"en": "Rototiller", "es": "Fertilizante"},
		{"en": "Lock-on", "es": "Fijar blanco"},
		{"en": "Precipice Blades", "es": "Filo del abismo"},
		{"en": "Feint Attack", "es": "Finta"},
		{"en": "Fissure", "es": "Fisura"},
		{"en": "Focus energy", "es": "Foco energía"},
		{"en": "Flash Cannon", "es": "Foco resplandor"},
		{"en": "Seed Flare", "es": "Fogonazo"},
		{"en": "Harden", "es": "Fortaleza"},
		{"en": "Sheer cold", "es": "Frío polar"},
		{"en": "Frustration", "es": "Frustración"},
		{"en": "Will-o-wisp", "es": "Fuego fatuo"},
		{"en": "Sacred fire", "es": "Fuego sagrado"},
		{"en": "Strength", "es": "Fuerza"},
		{"en": "Superpower", "es": "Fuerza bruta"},
		{"en": "Moonblast", "es": "Fuerza lunar"},
		{"en": "Land's Wrath", "es": "Fuerza telúrica"},
		{"en": "Rage", "es": "Furia"},
		{"en": "Dragon rage", "es": "Furia dragón"},
		{"en": "Sky uppercut", "es": "Gancho alto"},
		{"en": "Crush claw", "es": "Garra brutal"},
		{"en": "Dragon claw", "es": "Garra dragón"},
		{"en": "Metal claw", "es": "Garra metal"},
		{"en": "Shadow Claw", "es": "Garra umbría"},
		{"en": "Poison gas", "es": "Gas venenoso"},
		{"en": "Geomancy", "es": "Geocontrol"},
		{"en": "Giga Impact", "es": "Giga impacto"},
		{"en": "Giga drain", "es": "Gigadrenado"},
		{"en": "Gyro Ball", "es": "Giro bola"},
		{"en": "Fire spin", "es": "Giro fuego"},
		{"en": "Rapid spin", "es": "Giro rápido"},
		{"en": "Thrash", "es": "Golpe"},
		{"en": "Aerial ace", "es": "Golpe aéreo"},
		{"en": "Sucker Punch", "es": "Golpe bajo"},
		{"en": "Dual Chop", "es": "Golpe bis"},
		{"en": "Headbutt", "es": "Golpe cabeza"},
		{"en": "Heat Crash", "es": "Golpe calor"},
		{"en": "Body slam", "es": "Golpe cuerpo"},
		{"en": "Phantom Force", "es": "Golpe fantasma"},
		{"en": "Karate chop", "es": "Golpe karate"},
		{"en": "Rock smash", "es": "Golpe roca"},
		{"en": "Shadow Force", "es": "Golpe umbrío"},
		{"en": "Fury swipes", "es": "Golpes furia"},
		{"en": "Miracle Eye", "es": "Gran ojo"},
		{"en": "Hail", "es": "Granizo"},
		{"en": "Gravity", "es": "Gravedad"},
		{"en": "Growl", "es": "Gruñido"},
		{"en": "Chip Away", "es": "Guardia baja"},
		{"en": "Guillotine", "es": "Guillotina"},
		{"en": "Trick-or-Treat", "es": "Halloween"},
		{"en": "Hydro pump", "es": "Hidrobomba"},
		{"en": "Hydro cannon", "es": "Hidrocañón"},
		{"en": "Water sport", "es": "Hidrochorro"},
		{"en": "Water pulse", "es": "Hidropulso"},
		{"en": "Grass Knot", "es": "Hierba lazo"},
		{"en": "Hyper fang", "es": "Hiper colmillo"},
		{"en": "Hyper beam", "es": "Hiperrayo"},
		{"en": "Hypnosis", "es": "Hipnosis"},
		{"en": "Razor leaf", "es": "Hoja afilada"},
		{"en": "Leaf blade", "es": "Hoja aguda"},
		{"en": "Magical leaf", "es": "Hoja mágica"},
		{"en": "Bone club", "es": "Hueso palo"},
		{"en": "Bonemerang", "es": "Huesomerang"},
		{"en": "Lava Plume", "es": "Humareda"},
		{"en": "U-turn", "es": "Ida y vuelta"},
		{"en": "Facade", "es": "Imagen"},
		{"en": "Role play", "es": "Imitación"},
		{"en": "Thunder Shock", "es": "Impactrueno"},
		{"en": "Astonish", "es": "Impresionar"},
		{"en": "Inferno", "es": "Infierno"},
		{"en": "Hex", "es": "Infortunio"},
		{"en": "Skill swap", "es": "Intercambio"},
		{"en": "Reversal", "es": "Inversión"},
		{"en": "Power Split", "es": "Isofuerza"},
		{"en": "Guard Split", "es": "Isoguardia"},
		{"en": "Power Gem", "es": "Joya de luz"},
		{"en": "Foul Play", "es": "Juego sucio"},
		{"en": "Kinesis", "es": "Kinético"},
		{"en": "Thief", "es": "Ladrón"},
		{"en": "Gunk Shot", "es": "Lanza mugre"},
		{"en": "Flamethrower", "es": "Lanzallamas"},
		{"en": "Fling", "es": "Lanzamiento"},
		{"en": "Rock throw", "es": "Lanzarrocas"},
		{"en": "Power Whip", "es": "Latigazo"},
		{"en": "Tail whip", "es": "Látigo"},
		{"en": "Vine whip", "es": "Látigo cepa"},
		{"en": "Memento", "es": "Legado"},
		{"en": "Lick", "es": "Lengüetazo"},
		{"en": "Magnet Rise", "es": "Levitón"},
		{"en": "Freeze-Dry", "es": "Liofilización"},
		{"en": "Blue Flare", "es": "Llama azul"},
		{"en": "Mystical Fire", "es": "Llama embrujada"},
		{"en": "Fusion Flare", "es": "Llama fusión"},
		{"en": "Ice Burn", "es": "Llama gélida"},
		{"en": "Fire blast", "es": "Llamarada"},
		{"en": "Fake tears", "es": "Llanto falso"},
		{"en": "Storm Throw", "es": "Llave corsé"},
		{"en": "Circle Throw", "es": "Llave giro"},
		{"en": "Leaf Storm", "es": "Lluevehojas"},
		{"en": "Magma Storm", "es": "Lluvia ígnea"},
		{"en": "Light of Ruin", "es": "Luz aniquiladora"},
		{"en": "Moonlight", "es": "Luz lunar"},
		{"en": "Hammer Arm", "es": "Machada"},
		{"en": "Magnitude", "es": "Magnitud"},
		{"en": "Mean look", "es": "Mal de ojo"},
		{"en": "Curse", "es": "Maldición"},
		{"en": "Leer", "es": "Malicioso"},
		{"en": "Hold hands", "es": "Manos juntas"},
		{"en": "Mirror coat", "es": "Manto espejo"},
		{"en": "Nasty plot", "es": "Maquinación"},
		{"en": "Crabhammer", "es": "Martillazo"},
		{"en": "Psych up", "es": "Más psique"},
		{"en": "Cosmic power", "es": "Masa cósmica"},
		{"en": "Wood Hammer", "es": "Mazazo"},
		{"en": "Meditate", "es": "Meditación"},
		{"en": "Mega drain", "es": "Megaagotar"},
		{"en": "Megahorn", "es": "Megacuerno"},
		{"en": "Mega kick", "es": "Megapatada"},
		{"en": "Mega punch", "es": "Megapuño"},
		{"en": "Weather ball", "es": "Meteorobola"},
		{"en": "Metronome", "es": "Metrónomo"},
		{"en": "Mimic", "es": "Mimético"},
		{"en": "Destiny bond", "es": "Mismodestino"},
		{"en": "Taunt", "es": "Mofa"},
		{"en": "Nuzzle", "es": "Moflete estático"},
		{"en": "Bite", "es": "Mordisco"},
		{"en": "Mirror move", "es": "Movimiento espejo"},
		{"en": "Seismic toss", "es": "Movimiento sísmico"},
		{"en": "Glaciate", "es": "Mundo gélido"},
		{"en": "Mist", "es": "Neblina"},
		{"en": "Haze", "es": "Niebla"},
		{"en": "Aromatic Mist", "es": "Niebla aromática"},
		{"en": "Clear Smog", "es": "Niebla clara"},
		{"en": "Powder snow", "es": "Nieve polvo"},
		{"en": "Flame Charge", "es": "Nitrocarga"},
		{"en": "Bestow", "es": "Ofrenda"},
		{"en": "Baby-Doll Eyes", "es": "Ojitos tiernos"},
		{"en": "Eerie Impulse", "es": "Onda anómala"},
		{"en": "Focus Blast", "es": "Onda certera"},
		{"en": "Heat wave", "es": "Onda ígnea"},
		{"en": "Psystrike", "es": "Onda mental"},
		{"en": "Simple Beam", "es": "Onda simple"},
		{"en": "Sludge Wave", "es": "Onda tóxica"},
		{"en": "Thunder wave", "es": "Onda trueno"},
		{"en": "Vacuum Wave", "es": "Onda vacío"},
		{"en": "Shock wave", "es": "Onda voltio"},
		{"en": "Encore", "es": "Otra vez"},
		{"en": "Happy Hour", "es": "Paga extra"},
		{"en": "Brave Bird", "es": "Pájaro osado"},
		{"en": "Beat Up", "es": "Paliza"},
		{"en": "Force Palm", "es": "Palmeo"},
		{"en": "Light Screen", "es": "Pantalla luz"},
		{"en": "Smokescreen", "es": "Pantallahumo"},
		{"en": "Stun Spore", "es": "Paralizador"},
		{"en": "Extrasensory", "es": "Paranormal"},
		{"en": "Hyperspace Hole", "es": "Paso dimensional"},
		{"en": "Low Kick", "es": "Patada baja"},
		{"en": "Rolling Kick", "es": "Patada giro"},
		{"en": "Blaze Kick", "es": "Patada ígnea"},
		{"en": "Jump Kick", "es": "Patada salto"},
		{"en": "High Jump Kick", "es": "Patada salto alta"},
		{"en": "Calm Mind", "es": "Paz mental"},
		{"en": "Rock Blast", "es": "Pedrada"},
		{"en": "Horn Drill", "es": "Perforador"},
		{"en": "Pursuit", "es": "Persecución"},
		{"en": "Nightmare", "es": "Pesadilla"},
		{"en": "Bug Bite", "es": "Picadura"},
		{"en": "Drill Peck", "es": "Pico taladro"},
		{"en": "Peck", "es": "Picotazo"},
		{"en": "Poison Sting", "es": "Picotazo venenoso"},
		{"en": "Pluck", "es": "Picoteo"},
		{"en": "Pin Missile", "es": "Pin misil"},
		{"en": "Flame Burst", "es": "Pirotecnia"},
		{"en": "Stomp", "es": "Pisotón"},
		{"en": "Water Gun", "es": "Pistola agua"},
		{"en": "Tackle", "es": "Placaje"},
		{"en": "Volt Tackle", "es": "Placaje eléctrico"},
		{"en": "Flying Press", "es": "Plancha voladora"},
		{"en": "Frenzy Plant", "es": "Planta feroz"},
		{"en": "Tail Slap", "es": "Plumerazo"},
		{"en": "Hidden Power", "es": "Poder oculto"},
		{"en": "Ancient Power", "es": "Poder pasado"},
		{"en": "Stored Power", "es": "Poder reserva"},
		{"en": "Smog", "es": "Polución"},
		{"en": "Powder", "es": "Polvo explosivo"},
		{"en": "Rage Powder", "es": "Polvo ira"},
		{"en": "Poison Powder", "es": "Polvo veneno"},
		{"en": "Future Sight", "es": "Premonición"},
		{"en": "Barrage", "es": "Presa"},
		{"en": "Present", "es": "Presente"},
		{"en": "Foresight", "es": "Profecía"},
		{"en": "Protect", "es": "Protección"},
		{"en": "Psycho Shift", "es": "Psicocambio"},
		{"en": "Psycho Cut", "es": "Psicocorte"},
		{"en": "Psycho Boost", "es": "Psicoataque"},
		{"en": "Psyshock", "es": "Psicocarga"},
		{"en": "Psywave", "es": "Psicoonda"},
		{"en": "Psybeam", "es": "Psicorrayo"},
		{"en": "Psychic", "es": "Psíquico"},
		{"en": "Spikes", "es": "Púas"},
		{"en": "Toxic Spikes", "es": "Púas tóxicas"},
		{"en": "Rock Polish", "es": "Pulimento"},
		{"en": "Octazooka", "es": "Pulpocañón"},
		{"en": "Heal Pulse", "es": "Pulso cura"},
		{"en": "Dragon Pulse", "es": "Pulso dragón"},
		{"en": "Night Daze", "es": "Pulso noche"},
		{"en": "Origin Pulse", "es": "Pulso primigenio"},
		{"en": "Dark Pulse", "es": "Pulso umbrío"},
		{"en": "Low Sweep", "es": "Puntapié"},
		{"en": "Bullet Punch", "es": "Puño bala"},
		{"en": "Focus Punch", "es": "Puño certero"},
		{"en": "Comet Punch", "es": "Puño cometa"},
		{"en": "Drain Punch", "es": "Puño drenaje"},
		{"en": "Fire Punch", "es": "Puño fuego"},
		{"en": "Ice Punch", "es": "Puño hielo"},
		{"en": "Power-Up Punch", "es": "Puño incremento"},
		{"en": "Dizzy Punch", "es": "Puño mareo"},
		{"en": "Meteor Mash", "es": "Puño meteoro"},
		{"en": "Shadow Punch", "es": "Puño sombra"},
		{"en": "Thunder Punch", "es": "Puño trueno"},
		{"en": "Dynamic Punch", "es": "Puñodinámico"},
		{"en": "Poison Jab", "es": "Puya nociva"},
		{"en": "Grudge", "es": "Rabia"},
		{"en": "Tail Glow", "es": "Ráfaga"},
		{"en": "Swift", "es": "Rapidez"},
		{"en": "Odor Sleuth", "es": "Rastreo"},
		{"en": "Thunderbolt", "es": "Rayo"},
		{"en": "Aurora Beam", "es": "Rayo aurora"},
		{"en": "Bubble Beam", "es": "Rayo burbuja"},
		{"en": "Charge Beam", "es": "Rayo carga"},
		{"en": "Confuse Ray", "es": "Rayo confuso"},
		{"en": "Fusion Bolt", "es": "Rayo fusión"},
		{"en": "Freeze Shock", "es": "Rayo gélido"},
		{"en": "Ice Beam", "es": "Rayo hielo"},
		{"en": "Solar Beam", "es": "Rayo solar"},
		{"en": "Recycle", "es": "Reciclaje"},
		{"en": "Recover", "es": "Recuperación"},
		{"en": "Bullet Seed", "es": "Recurrente"},
		{"en": "Minimize", "es": "Reducción"},
		{"en": "Sticky Web", "es": "Red viscosa"},
		{"en": "Reflect", "es": "Reflejo"},
		{"en": "Helping Hand", "es": "Refuerzo"},
		{"en": "Withdraw", "es": "Refugio"},
		{"en": "Slack Off", "es": "Relajo"},
		{"en": "Baton Pass", "es": "Relevo"},
		{"en": "Whirlwind", "es": "Remolino"},
		{"en": "Spite", "es": "Rencor"},
		{"en": "Metal Burst", "es": "Represión metal"},
		{"en": "Retaliate", "es": "Represalia"},
		{"en": "Stockpile", "es": "Reserva"},
		{"en": "Sludge", "es": "Residuos"},
		{"en": "Roost", "es": "Respiro"},
		{"en": "Luster Purge", "es": "Resplandor"},
		{"en": "Constrict", "es": "Restricción"},
		{"en": "Return", "es": "Retribución"},
		{"en": "Topsy-Turvy", "es": "Reversión"},
		{"en": "Cotton Guard", "es": "Rizo algodón"},
		{"en": "Defense Curl", "es": "Rizo defensa"},
		{"en": "Snatch", "es": "Robo"},
		{"en": "Stone Edge", "es": "Roca afilada"},
		{"en": "Steamroller", "es": "Rodillo de púas"},
		{"en": "Shell Smash", "es": "Rompecoraza"},
		{"en": "Rock Wrecker", "es": "Romperrocas"},
		{"en": "Snore", "es": "Ronquido"},
		{"en": "Gear Grind", "es": "Rueda doble"},
		{"en": "Flame Wheel", "es": "Rueda fuego"},
		{"en": "Roar", "es": "Rugido"},
		{"en": "Noble Roar", "es": "Rugido de guerra"},
		{"en": "Secret Sword", "es": "Sable místico"},
		{"en": "Final Gambit", "es": "Sacrificio"},
		{"en": "Brine", "es": "Salmuera"},
		{"en": "Splash", "es": "Salpicadura"},
		{"en": "Water Spout", "es": "Salpicar"},
		{"en": "Captivate", "es": "Seducción"},
		{"en": "Judgment", "es": "Sentencia"},
		{"en": "Follow Me", "es": "Señuelo"},
		{"en": "Water Shuriken", "es": "Shuriken de agua"},
		{"en": "Grass Whistle", "es": "Silbato"},
		{"en": "Synchronoise", "es": "Sincrorruido"},
		{"en": "Synthesis", "es": "Síntesis"},
		{"en": "Overheat", "es": "Sofoco"},
		{"en": "Morning Sun", "es": "Sol matinal"},
		{"en": "Shadow Sneak", "es": "Sombra vil"},
		{"en": "Sleep Powder", "es": "Somnífero"},
		{"en": "Sleep Talk", "es": "Sonámbulo"},
		{"en": "Fake Out", "es": "Sorpresa"},
		{"en": "Submission", "es": "Sumisión"},
		{"en": "Super Fang", "es": "Superdiente"},
		{"en": "Supersonic", "es": "Supersónico"},
		{"en": "Surf", "es": "Surf"},
		{"en": "Substitute", "es": "Sustituto"},
		{"en": "Air Slash", "es": "Tajo aéreo"},
		{"en": "Cross Chop", "es": "Tajo cruzado"},
		{"en": "Night Slash", "es": "Tajo umbrío"},
		{"en": "Drill Run", "es": "Taladradora"},
		{"en": "Belly Drum", "es": "Tambor"},
		{"en": "Techno Blast", "es": "Tecno shock"},
		{"en": "Spider Web", "es": "Telaraña"},
		{"en": "Mind Reader", "es": "Telépata"},
		{"en": "Telekinesis", "es": "Telequinesis"},
		{"en": "Teleport", "es": "Teletransporte"},
		{"en": "Clamp", "es": "Tenaza"},
		{"en": "Bulldoze", "es": "Terratemblor"},
		{"en": "Earthquake", "es": "Terremoto"},
		{"en": "Head Smash", "es": "Testarazo"},
		{"en": "Earth Power", "es": "Tierra viva"},
		{"en": "X-Scissor", "es": "Tijera X"},
		{"en": "Night shade", "es": "Tinieblas"},
		{"en": "Vital Throw", "es": "Tiro vital"},
		{"en": "Whirlpool", "es": "Torbellino"},
		{"en": "Sandstorm", "es": "Tormenta arena"},
		{"en": "Diamond Storm", "es": "Tormenta de diamantes"},
		{"en": "Petal Blizzard", "es": "Tormenta floral"},
		{"en": "Torment", "es": "Tormento"},
		{"en": "Gust", "es": "Tornado"},
		{"en": "Toxic", "es": "Tóxico"},
		{"en": "Swallow", "es": "Tragar"},
		{"en": "Stealth Rock", "es": "Trampa rocas"},
		{"en": "Venom Drench", "es": "Trampa venenosa"},
		{"en": "Transform", "es": "Transformación"},
		{"en": "Switcheroo", "es": "Trapicheo"},
		{"en": "Rock Climb", "es": "Treparrocas"},
		{"en": "Tri Attack", "es": "Triataque"},
		{"en": "Triple Kick", "es": "Triple patada"},
		{"en": "Crunch", "es": "Triturar"},
		{"en": "Trick", "es": "Truco"},
		{"en": "Crafty Shield", "es": "Truco defensa"},
		{"en": "Power Trick", "es": "Truco fuerza"},
		{"en": "Thunder", "es": "Trueno"},
		{"en": "Rock tomb", "es": "Tumba rocas"},
		{"en": "Last Resort", "es": "Última baza"},
		{"en": "Parting Shot", "es": "Última palabra"},
		{"en": "Quash", "es": "Último lugar"},
		{"en": "Mach Punch", "es": "Ultrapuño"},
		{"en": "V-create", "es": "V de fuego"},
		{"en": "Frost Breath", "es": "Vaho gélido"},
		{"en": "Wide Guard", "es": "Vastaguardia"},
		{"en": "Safeguard", "es": "Velo sagrado"},
		{"en": "Extreme Speed", "es": "Velocidad extrema"},
		{"en": "Hurricane", "es": "Vendaval"},
		{"en": "Payback", "es": "Vendetta"},
		{"en": "Cross Poison", "es": "Veneno X"},
		{"en": "Bide", "es": "Venganza"},
		{"en": "Blizzard", "es": "Ventisca"},
		{"en": "Ominous Wind", "es": "Viento aciago"},
		{"en": "Tailwind", "es": "Viento afín"},
		{"en": "Razor Wind", "es": "Viento cortante"},
		{"en": "Fairy Wind", "es": "Viento feérico"},
		{"en": "Icy Wind", "es": "Viento hielo"},
		{"en": "Silver Wind", "es": "Viento plata"},
		{"en": "Wild Charge", "es": "Voltio cruel"},
		{"en": "Volt Switch", "es": "Voltiocambio"},
		{"en": "Water Pledge", "es": "Voto agua"},
		{"en": "Fire Pledge", "es": "Voto fuego"},
		{"en": "Grass Pledge", "es": "Voto planta"},
		{"en": "Hyper voice", "es": "Vozarrón"},
		{"en": "Disarming Voice", "es": "Voz cautivadora"},
		{"en": "Fly", "es": "Vuelo"},
		{"en": "Me First", "es": "Yo primero"},
		{"en": "Wonder Room", "es": "Zona extraña"},
		{"en": "Magic Room", "es": "Zona mágica"},
		{"en": "Bug Buzz", "es": "Zumbido"}
	],
	"item": [
		{"en": "absorb bulb", "es": "bulbo"},
		{"en": "adamant orb", "es": "adamasfera"},
		{"en": "air balloon", "es": "palloncino"},
		{"en": "amulet coin", "es": "monetamuleto"},
		{"en": "assault vest", "es": "corpetto assalto"},
		{"en": "berry juice", "es": " succo di bacca"},
		{"en": "berserk gene", "es": "gene furioso"},
		{"en": "big root", "es": "granradice"},
		{"en": "binding band", "es": "legafascia"},
		{"en": "black belt", "es": "cinturanera"},
		{"en": "black glasses", "es": "occhialineri"},
		{"en": "black sludge", "es": "fangopece"},
		{"en": "blue scarf", "es": "fascia blu"},
		{"en": "bright powder", "es": "luminpolvere"},
		{"en": "bug gem", "es": "bijoucoleot,"},
		{"en": "burn drive", "es": "piromodulo"},
		{"en": "cell battery", "es": "ricaripila"},
		{"en": "charcoal", "es": "carbonella"},
		{"en": "chill drive", "es": "gelomodulo"},
		{"en": "choice band", "es": "bendascelta"},
		{"en": "choice scarf", "es": "stolascelta"},
		{"en": "choice specs", "es": "lentiscelta"},
		{"en": "cleanse tag", "es": "velopuro"},
		{"en": "damp rock", "es": "rocciaumida"},
		{"en": "dark gem", "es": "bijoubuio"},
		{"en": "deep sea scale", "es": "squamabissi"},
		{"en": "deep sea tooth", "es": "denteabissi"},
		{"en": "destiny knot", "es": "destincomune"},
		{"en": "douse drive", "es": "idromodulo"},
		{"en": "draco plate", "es": "lastradrakon"},
		{"en": "dragon fang", "es": "dentedidrago"},
		{"en": "dragon gem", "es": "bijoudrago"},
		{"en": "dragon scale", "es": "squama drago"},
		{"en": "dread plate", "es": "lastratimore"},
		{"en": "dubious disc", "es": "dubbiodisco"},
		{"en": "earth plate", "es": "lastrageo"},
		{"en": "eject button", "es": "pulsantefuga"},
		{"en": "electirizer", "es": "elettritore"},
		{"en": "electric gem", "es": "bijouelettro"},
		{"en": "everstone", "es": "pietrastante"},
		{"en": "eviolite", "es": "evolcondensa"},
		{"en": "exp, share", "es": "condividi esp,*"},
		{"en": "expert belt", "es": "abilcintura"},
		{"en": "fighting gem", "es": "bijoulotta"},
		{"en": "fire gem", "es": "bijoufuoco"},
		{"en": "fist plate", "es": "lastrapugno"},
		{"en": "flame orb", "es": "fiammosfera"},
		{"en": "flame plate", "es": "lastrarogo"},
		{"en": "float stone", "es": "pietralieve"},
		{"en": "flying gem", "es": "bijouvolante"},
		{"en": "focus band", "es": "bandana"},
		{"en": "focus sash", "es": "focalnastro"},
		{"en": "fresh water", "es": "acqua fresca"},
		{"en": "full incense", "es": "gonfioaroma"},
		{"en": "ghost gem", "es": "bijouspettro"},
		{"en": "grass gem", "es": "bijouerba"},
		{"en": "green scarf", "es": "fascia verde"},
		{"en": "grip claw", "es": "presartigli"},
		{"en": "griseous orb", "es": "grigiosfera"},
		{"en": "ground gem", "es": "bijouterra"},
		{"en": "hard stone", "es": "pietradura"},
		{"en": "heat rock", "es": "rocciacalda"},
		{"en": "ice gem", "es": "bijoughiac,"},
		{"en": "icicle plate", "es": "lastragelo"},
		{"en": "icy rock", "es": "rocciafredda"},
		{"en": "insect plate", "es": "lastrabaco"},
		{"en": "iron ball", "es": "ferropalla"},
		{"en": "iron plate", "es": "lastraferro"},
		{"en": "king's rock", "es": "roccia di re"},
		{"en": "lagging tail", "es": "rallentocoda"},
		{"en": "lax incense", "es": "distraroma"},
		{"en": "leftovers", "es": "avanzi"},
		{"en": "lemonade", "es": "lemonsucco"},
		{"en": "life orb", "es": "assorbisfera"},
		{"en": "light ball", "es": "elettropalla"},
		{"en": "light clay", "es": "creta luce"},
		{"en": "luck incense", "es": "fortunaroma"},
		{"en": "lucky egg", "es": "fortunuovo"},
		{"en": "lucky punch", "es": "fortunpugno"},
		{"en": "lustrous orb", "es": "splendisfera"},
		{"en": "macho brace", "es": "crescicappa"},
		{"en": "magmarizer", "es": "magmatore"},
		{"en": "magnet", "es": "calamita"},
		{"en": "meadow plate", "es": "lastraprato"},
		{"en": "mental herb", "es": "mentalerba"},
		{"en": "metal coat", "es": "metalcoperta"},
		{"en": "metal powder", "es": "metalpolvere"},
		{"en": "metronome", "es": "plessimetro"},
		{"en": "mind plate", "es": "lastramente"},
		{"en": "miracle seed", "es": "miracolseme"},
		{"en": "moomoo milk", "es": "latte mumu"},
		{"en": "muscle band", "es": "muscolbanda"},
		{"en": "mystic water", "es": "acquamagica"},
		{"en": "never-melt ice", "es": "gelomai"},
		{"en": "normal gem", "es": "bijounormale"},
		{"en": "odd incense", "es": "bizzoaroma"},
		{"en": "pink bow", "es": "fiocco rosa"},
		{"en": "pink scarf", "es": "fascia rosa"},
		{"en": "poison barb", "es": "velenago"},
		{"en": "poison gem", "es": "bijouveleno"},
		{"en": "polkadot bow", "es": "fiocco pois"},
		{"en": "power anklet", "es": "vigorgliera"},
		{"en": "power band", "es": "vigorbanda"},
		{"en": "power belt", "es": "vigorfascia"},
		{"en": "power bracer", "es": "vigorcerchio"},
		{"en": "power herb", "es": "vigorerba"},
		{"en": "power lens", "es": "vigorlente"},
		{"en": "power weight", "es": "vigorpeso"},
		{"en": "prism scale", "es": "squama bella"},
		{"en": "protector", "es": "copertura"},
		{"en": "psychic gem", "es": "bijoupsico"},
		{"en": "pure incense", "es": "puroaroma"},
		{"en": "quick claw", "es": "rapidartigli"},
		{"en": "quick powder", "es": "velopolvere"},
		{"en": "razor claw", "es": "affilartigli"},
		{"en": "razor fang", "es": "affilodente"},
		{"en": "reaper cloth", "es": "terrorpanno"},
		{"en": "red card", "es": "cartelrosso"},
		{"en": "red scarf", "es": "fascia rossa"},
		{"en": "ring target", "es": "facilsaglio"},
		{"en": "rock gem", "es": "bijouroccia"},
		{"en": "rock incense", "es": "roccioaroma"},
		{"en": "rocky helmet", "es": "bitorzolelmo"},
		{"en": "rose incense", "es": "rosaroma"},
		{"en": "safety goggles", "es": "visierantisabbia"},
		{"en": "scope lens", "es": "mirino"},
		{"en": "sea incense", "es": "marearoma"},
		{"en": "sharp beak", "es": "beccaffilato"},
		{"en": "shed shell", "es": "disfoguscio"},
		{"en": "shell bell", "es": "conchinella"},
		{"en": "shock drive", "es": "voltmodulo"},
		{"en": "silk scarf", "es": "sciarpaseta"},
		{"en": "silver powder", "es": "argenpolvere"},
		{"en": "sky plate", "es": "lastracielo"},
		{"en": "smoke ball", "es": "palla fumo"},
		{"en": "smooth rock", "es": "roccialiscia"},
		{"en": "snowball", "es": "palla di neve"},
		{"en": "soda pop", "es": "gassosa"},
		{"en": "soft sand", "es": "sabbiasoffice"},
		{"en": "soothe bell", "es": "calmanella"},
		{"en": "soul dew", "es": "cuorugiada"},
		{"en": "spell tag", "es": "spettrotarga"},
		{"en": "splash plate", "es": "lastraidro"},
		{"en": "spooky plate", "es": "lastratetra"},
		{"en": "steel gem", "es": "bijouacciaio"},
		{"en": "stick", "es": "gambo"},
		{"en": "sticky barb", "es": "vischiopunta"},
		{"en": "stone plate", "es": "lastrapietra"},
		{"en": "tea", "es": "tè"},
		{"en": "thick club", "es": "ossospesso"},
		{"en": "toxic orb", "es": "tossicsfera"},
		{"en": "toxic plate", "es": "lastrafiele"},
		{"en": "twisted spoon", "es": "cucchiaiotorto"},
		{"en": "up-grade", "es": "upgrade"},
		{"en": "water gem", "es": "bijouacqua"},
		{"en": "wave incense", "es": "ondaroma"},
		{"en": "weakness policy", "es": "vulneropolizza"},
		{"en": "whipped dream", "es": "dolcespuma"},
		{"en": "white herb", "es": "erbachiara"},
		{"en": "wide lens", "es": "grandelente"},
		{"en": "wise glasses", "es": "saviocchiali"},
		{"en": "yellow scarf", "es": "fascia gialla"},
		{"en": "zap plate", "es": "lastrasaetta"},
		{"en": "zoom lens", "es": "zoomlente"}
	],
	"berry": [
		{"en": "aguav berry", "es": "Baya Guaya"},
		{"en": "apicot berry", "es": "Baya Aricoc"},
		{"en": "aspear berry", "es": "Baya Perasi"},
		{"en": "babiri berry", "es": "Baya Baribá"},
		{"en": "belue berry", "es": "Baya Andano"},
		{"en": "bluk berry", "es": "Baya Oram"},
		{"en": "charti berry", "es": "Baya Alcho"},
		{"en": "cheri berry", "es": "Baya Zreza"},
		{"en": "chesto berry", "es": "Baya Atania"},
		{"en": "chilan berry", "es": "Baya Chilan"},
		{"en": "chople berry", "es": "Baya Pomaro"},
		{"en": "coba berry", "es": "Baya Kouba"},
		{"en": "colbur berry", "es": "Baya Dillo"},
		{"en": "cornn berry", "es": "Baya Mais"},
		{"en": "custap berry", "es": "Baya Chiri"},
		{"en": "durin berry", "es": "Baya Rudion"},
		{"en": "enigma berry", "es": "Baya Enigma"},
		{"en": "figy berry", "es": "Baya Higog"},
		{"en": "ganlon berry", "es": "Baya Gonlan"},
		{"en": "grepa berry", "es": "Baya Uvav"},
		{"en": "haban berry", "es": "Baya Anjiro"},
		{"en": "hondew berry", "es": "Baya Meluce"},
		{"en": "iapapa berry", "es": "Baya Pabaya"},
		{"en": "jaboca berry", "es": "Baya Jaboca"},
		{"en": "kasib berry", "es": "Baya Drasi"},
		{"en": "kebia berry", "es": "Baya Kebia"},
		{"en": "kee berry", "es": "Baya Biglia"},
		{"en": "kelpsy berry", "es": "Baya Algama"},
		{"en": "lansat berry", "es": "Baya Zonlan"},
		{"en": "leppa berry", "es": "Baya Zanama"},
		{"en": "liechi berry", "es": "Baya Lichi"},
		{"en": "lum berry", "es": "Baya Ziuela"},
		{"en": "mago berry", "es": "Baya Ango"},
		{"en": "magost berry", "es": "Baya Aostan"},
		{"en": "maranga berry", "es": "Baya Maranga"},
		{"en": "micle berry", "es": "Baya Lagro"},
		{"en": "nanab berry", "es": "Baya Latano"},
		{"en": "nomel berry", "es": "Baya Monli"},
		{"en": "occa berry", "es": "Baya Caoca"},
		{"en": "oran berry", "es": "Baya Aranka"},
		{"en": "pamtre berry", "es": "Baya Plama"},
		{"en": "passho berry", "es": "Baya Basio"},
		{"en": "payapa berry", "es": "Baya Payapa"},
		{"en": "pecha berry", "es": "Baya Meloc"},
		{"en": "persim berry", "es": "Baya Caquic"},
		{"en": "petaya berry", "es": "Baya Yapati"},
		{"en": "pinap berry", "es": "Baya Pinia"},
		{"en": "pomeg berry", "es": "Baya Grana"},
		{"en": "qualot berry", "es": "Baya Ispero"},
		{"en": "rabuta berry", "es": "Baya Rautan"},
		{"en": "rawst berry", "es": "Baya Safre"},
		{"en": "razz berry", "es": "Baya Frambu"},
		{"en": "rindo berry", "es": "Baya Tamar"},
		{"en": "roseli berry", "es": "Baya Hibis"},
		{"en": "rowap berry", "es": "Baya Magua"},
		{"en": "salac berry", "es": "Baya Aslac"},
		{"en": "shuca berry", "es": "Baya Acardo"},
		{"en": "sitrus berry", "es": "Baya Zidra"},
		{"en": "spelon berry", "es": "Baya Wikano"},
		{"en": "starf berry", "es": "Baya Arabol"},
		{"en": "tamato berry", "es": "Baya Tamate"},
		{"en": "tanga berry", "es": "Baya Yecana"},
		{"en": "wacan berry", "es": "Baya Gualot"},
		{"en": "watmel berry", "es": "Baya Sambia"},
		{"en": "wepear berry", "es": "Baya Peragu"},
		{"en": "wiki berry", "es": "Baya Wiki"},
		{"en": "yache berry", "es": "Baya Rimoya"}
	],
	"megastone" : [
		{"en": "abomasite", "es": "abomasnowite"},
		{"en": "absolite", "es": "absolite"},
		{"en": "aerodactylite", "es": "aerodactylite"},
		{"en": "aggronite", "es": "aggronite"},
		{"en": "alakazite", "es": "alakazamite"},
		{"en": "ampharosite", "es": "ampharosite"},
		{"en": "banettite", "es": "banettite"},
		{"en": "blastoisinite", "es": "blastoisite"},
		{"en": "blazikenite", "es": "blazikenite"},
		{"en": "charizardite x", "es": "charizardite x"},
		{"en": "charizardite y", "es": "charizardite y"},
		{"en": "diancite", "es": "diancite"},
		{"en": "garchompite", "es": "garchompite"},
		{"en": "gardevoirite", "es": "gardevoirite"},
		{"en": "gengarite", "es": "gengarite"},
		{"en": "glalitite", "es": "glalite"},
		{"en": "gyaradosite", "es": "gyaradosite"},
		{"en": "heracronite", "es": "heracrossite"},
		{"en": "houndoominite", "es": "houndoomite"},
		{"en": "kangaskhanite", "es": "kangaskhanite"},
		{"en": "latiasite", "es": "latiasite"},
		{"en": "latiosite", "es": "latiosite"},
		{"en": "lucarionite", "es": "lucarite"},
		{"en": "manectite", "es": "manectricite"},
		{"en": "mawilite", "es": "mawilite"},
		{"en": "medichamite", "es": "medichamite"},
		{"en": "metagrossite", "es": "metagrossite"},
		{"en": "mewtwonite x", "es": "mewtwoite x"},
		{"en": "mewtwonite y", "es": "mewtwoite y"},
		{"en": "pinsirite", "es": "pinsirite"},
		{"en": "sceptilite", "es": "sceptilite"},
		{"en": "scizorite", "es": "scizorite"},
		{"en": "steelixite", "es": "steelixite"},
		{"en": "swampertite", "es": "swampertite"},
		{"en": "tyranitarite", "es": "tyranitarite"},
		{"en": "venusaurite", "es": "venusaurite"}
	],
	"nature": [
                {"en": "adamant", "es": "Firme"},
                {"en": "bashful", "es": "Tímida"},
                {"en": "bold", "es": "Osada"},
                {"en": "brave", "es": "Audaz"},
                {"en": "calm", "es": "Serena"},
                {"en": "careful", "es": "Cauta"},
                {"en": "docile", "es": "Dócil"},
                {"en": "gentle", "es": "Amable"},
                {"en": "hardy", "es": "Fuerte"},
                {"en": "hasty", "es": "Activa"},
                {"en": "impish", "es": "Agitada"},
                {"en": "jolly", "es": "Alegre"},
                {"en": "lax", "es": "Floja"},
                {"en": "lonely", "es": "Huraña"},
                {"en": "mild", "es": "Afable"},
                {"en": "modest", "es": "Modesta"},
                {"en": "naive", "es": "Ingenua"},
                {"en": "naughty", "es": "Pícara"},
                {"en": "quiet", "es": "Mansa"},
                {"en": "quirky", "es": "Rara"},
                {"en": "rash", "es": "Alocada"},
                {"en": "relaxed", "es": "Plácida"},
                {"en": "sassy", "es": "Grosera"},
                {"en": "serious", "es": "Seria"},
                {"en": "timid", "es": "Miedosa"}
	]
};
