exports.trad = {
	"ability": [
		{"en": "adaptability", "es": "adaptable"},
		{"en": "aerilate", "es": "Piel Celeste"},
		{"en": "aftermath", "es": "Resquicio"},
		{"en": "air lock", "es": "Bucle aire"},
		{"en": "analytic", "es": "Cálculo final"},
		{"en": "anger point", "es": "Irascible"},
		{"en": "anticipation", "es": "Anticipación"},
		{"en": "arena trap", "es": "Trampa arena"},
		{"en": "aroma veil", "es": "Velo aroma"},
		{"en": "aura break", "es": "Rompeaura"},
		{"en": "bad dreams", "es": "Mal sueño"},
		{"en": "battle armor", "es": "Armadura batalla"},
		{"en": "big pecks", "es": "Sacapecho"},
		{"en": "blaze", "es": "Mar llamas"},
		{"en": "bulletproof", "es": "Antibalas"},
		{"en": "cheek pouch", "es": "Carrillo"},
		{"en": "chlorophyll", "es": "Clorofila"},
		{"en": "clear body", "es": "Cuerpo puro"},
		{"en": "cloud nine", "es": "Aclimatación"},
		{"en": "color change", "es": "Cambio color"},
		{"en": "competitive", "es": "Tenacidad"},
		{"en": "compoundeyes", "es": "Ojocompuesto"},
		{"en": "contrary", "es": "Respondón"},
		{"en": "cursed body", "es": "Cuerpo maldito"},
		{"en": "cute charm", "es": "Gran encanto"},
		{"en": "damp", "es": "Humedad"},
		{"en": "dark aura", "es": "Aura oscura"},
		{"en": "defeatist", "es": "Flaqueza"},
		{"en": "defiant", "es": "Competitivo"},
		{"en": "delta stream", "es": "Ráfaga delta"},
		{"en": "desolate land", "es": "Tierra del ocaso"},
		{"en": "download", "es": "Descarga"},
		{"en": "drizzle", "es": "Llovizna"},
		{"en": "drought", "es": "Sequía"},
		{"en": "dry skin", "es": "Piel seca"},
		{"en": "early bird", "es": "Madrugar"},
		{"en": "effect spore", "es": "Efecto espora"},
		{"en": "fairy aura", "es": "Aura feérica"},
		{"en": "filter", "es": "Fitro"},
		{"en": "flame body", "es": "Cuerpo llama"},
		{"en": "flare boost", "es": "Ímpetu ardiente"},
		{"en": "flash fire", "es": "Absorbe fuego"},
		{"en": "flower gift", "es": "Don floral"},
		{"en": "flower veil", "es": "Velo flor"},
		{"en": "forecast", "es": "Predicción"},
		{"en": "forewarn", "es": "Alerta"},
		{"en": "friend guard", "es": "Compiescolta"},
		{"en": "frisk", "es": "Cacheo"},
		{"en": "fur coat", "es": "Pelaje recio"},
		{"en": "gale wings", "es": "Alas vendaval"},
		{"en": "gluttony", "es": "Gula"},
		{"en": "gooey", "es": "Baba"},
		{"en": "grass pelt", "es": "Manto frondoso"},
		{"en": "guts", "es": "Agallas"},
		{"en": "harvest", "es": "Cosecha"},
		{"en": "healer", "es": "Alma cura"},
		{"en": "heatproof", "es": "Ignífugo"},
		{"en": "heavy metal", "es": "Metal pesado"},
		{"en": "honey gather", "es": "Recogemiel"},
		{"en": "huge power", "es": "Potencia"},
		{"en": "hustle", "es": "Entusiasmo"},
		{"en": "hydration", "es": "Hidratación"},
		{"en": "hyper cutter", "es": "Corte fuerte"},
		{"en": "ice body", "es": "Gélido"},
		{"en": "illuminate", "es": "Iluminación"},
		{"en": "illusion", "es": "Ilusión"},
		{"en": "immunity", "es": "Inmunidad"},
		{"en": "imposter", "es": "Impostor"},
		{"en": "infiltrator", "es": "Allanamiento"},
		{"en": "inner focus", "es": "Foco interno"},
		{"en": "insomnia", "es": "Insomnio"},
		{"en": "intimidate", "es": "Intimidación"},
		{"en": "iron barbs", "es": "Punta acero"},
		{"en": "iron fist", "es": "Puño férreo"},
		{"en": "justified", "es": "Justiciero"},
		{"en": "keen eye", "es": "Vista Lince"},
		{"en": "klutz", "es": "Zoquete"},
		{"en": "leaf guard", "es": "Defensa hoja"},
		{"en": "levitate", "es": "Levitación"},
		{"en": "light metal", "es": "Metal liviano"},
		{"en": "lightningrod", "es": "Pararrayos"},
		{"en": "limber", "es": "Flexibilidad"},
		{"en": "liquid ooze", "es": "Lodo líquido"},
		{"en": "magic bounce", "es": "Esoejo mágico"},
		{"en": "magic guard", "es": "Muro mágico"},
		{"en": "magician", "es": "Prestidigitador"},
		{"en": "magma armor", "es": "Escudo magma"},
		{"en": "magnet pull", "es": "Imán"},
		{"en": "marvel scale", "es": "Escama especial"},
		{"en": "mega launcher", "es": "Megadisparador"},
		{"en": "minus", "es": "Menos"},
		{"en": "mold breaker", "es": "Rompemoldes"},
		{"en": "moody", "es": "Veleta"},
		{"en": "motor drive", "es": "Electromotor"},
		{"en": "moxie", "es": "Autoestima"},
		{"en": "multiscale", "es": "Compensación"},
		{"en": "multitype", "es": "Multitipo"},
		{"en": "mummy", "es": "Momia"},
		{"en": "natural cure", "es": "alternacura"},
		{"en": "no guard", "es": "nullodifesa"},
		{"en": "normalize", "es": "normalità"},
		{"en": "oblivious", "es": "indifferenza"},
		{"en": "overcoat", "es": "copricapo"},
		{"en": "overgrow", "es": "erbaiuto"},
		{"en": "own tempo", "es": "mente locale"},
		{"en": "parental bond", "es": "amorefiliale"},
		{"en": "pickpocket", "es": "arraffalesto"},
		{"en": "pickup", "es": "raccolta"},
		{"en": "plus", "es": "più"},
		{"en": "pixilate", "es": "pellefolletto"},
		{"en": "poison heal", "es": "velencura"},
		{"en": "poison point", "es": "velenopunto"},
		{"en": "poison touch", "es": "velentocco"},
		{"en": "prankster", "es": "burla"},
		{"en": "pressure", "es": "pressione"},
		{"en": "primordial sea", "es": "mare primordiale"},
		{"en": "protean", "es": "mutatipo"},
		{"en": "pure power", "es": "forzapura"},
		{"en": "quick feet", "es": "piedisvelti"},
		{"en": "rain dish", "es": "copripioggia"},
		{"en": "rattled", "es": "paura"},
		{"en": "reckless", "es": "temerarietà"},
		{"en": "refrigerate", "es": "pellegelo"},
		{"en": "regenerator", "es": "rigenergia"},
		{"en": "rivalry", "es": "antagonismo"},
		{"en": "rock head", "es": "testadura"},
		{"en": "rough skin", "es": "cartavetro"},
		{"en": "run away", "es": "fugafacile"},
		{"en": "sand force", "es": "silicoforza"},
		{"en": "sand rush", "es": "remasabbia"},
		{"en": "sand stream", "es": "sabbia fiume"},
		{"en": "sand veil", "es": "sabbiavelo"},
		{"en": "sap sipper", "es": "mangiaerba"},
		{"en": "scrappy", "es": "nervisaldi"},
		{"en": "serene grace", "es": "leggiadro"},
		{"en": "shadow tag", "es": "pedinombra"},
		{"en": "shed skin", "es": "muta"},
		{"en": "sheer force", "es": "forzabruta"},
		{"en": "shell armor", "es": "guscioscudo"},
		{"en": "shield dust", "es": "polvoscudo"},
		{"en": "simple", "es": "disinvoltura"},
		{"en": "skill link", "es": "abillegame"},
		{"en": "slow start", "es": "lentoinizio"},
		{"en": "sniper", "es": "cecchino"},
		{"en": "snow cloak", "es": "mantelneve"},
		{"en": "snow warning", "es": "scendineve"},
		{"en": "solar power", "es": "solarpotere"},
		{"en": "solid rock", "es": "solidroccia"},
		{"en": "soundproof", "es": "antisuono"},
		{"en": "speed boost", "es": "acceleratore"},
		{"en": "stall", "es": "rallentatore"},
		{"en": "stance change", "es": "accendilotta"},
		{"en": "static", "es": "statico"},
		{"en": "steadfast", "es": "cuordeciso"},
		{"en": "stench", "es": "tanfo"},
		{"en": "sticky hold", "es": "antifurto"},
		{"en": "storm drain", "es": "acquascolo"},
		{"en": "strong jaw", "es": "ferromascella"},
		{"en": "sturdy", "es": "vigore"},
		{"en": "suction cups", "es": "ventose"},
		{"en": "super luck", "es": "supersorte"},
		{"en": "swarm", "es": "aiutinsetto"},
		{"en": "sweet veil", "es": "dolcevelo"},
		{"en": "swift swim", "es": "nuotovelox"},
		{"en": "symbiosis", "es": "simbiosi"},
		{"en": "synchronize", "es": "sincronismo"},
		{"en": "tangled feet", "es": "intricopiedi"},
		{"en": "technician", "es": "tecnico"},
		{"en": "telepathy", "es": "telepatia"},
		{"en": "teravolt", "es": "teravolt"},
		{"en": "thick fat", "es": "grassospesso"},
		{"en": "tinted lens", "es": "lentifumé"},
		{"en": "torrent", "es": "acquaiuto"},
		{"en": "tough claws", "es": "unghiedure"},
		{"en": "toxic boost", "es": "velenimpeto"},
		{"en": "trace", "es": "traccia"},
		{"en": "truant", "es": "pigrizia"},
		{"en": "turboblaze", "es": "piroturbina"},
		{"en": "unaware", "es": "imprudenza"},
		{"en": "unburden", "es": "agiltecnica"},
		{"en": "unnerve", "es": "agitazione"},
		{"en": "victory star", "es": "tinovictoria"},
		{"en": "vital spirit", "es": "spiritovivo"},
		{"en": "volt absorb", "es": "assorbivolt"},
		{"en": "water absorb", "es": "assorbiacqua"},
		{"en": "water veil", "es": "idrovelo"},
		{"en": "weak armor", "es": "sottilguscio"},
		{"en": "white smoke", "es": "fumochiaro"},
		{"en": "wonder guard", "es": "magidifesa"},
		{"en": "wonder skin", "es": "splendicute"},
		{"en": "zen mode", "es": "stato zen"}
	],
	"move": [
		{"en": "absorb", "es": "assorbimento"},
		{"en": "acid armor", "es": "scudo acido"},
		{"en": "acid spray", "es": "acidobomba"},
		{"en": "acid", "es": "acido"},
		{"en": "acrobatics", "es": "acrobazia"},
		{"en": "acupressure", "es": "acupressione"},
		{"en": "aerial ace", "es": "aeroassalto"},
		{"en": "aeroblast", "es": "aerocolpo"},
		{"en": "after you", "es": "cortesia"},
		{"en": "agility", "es": "agilità"},
		{"en": "air cutter", "es": "aerasoio"},
		{"en": "air slash", "es": "eterelama"},
		{"en": "ally switch", "es": "cambiaposto"},
		{"en": "amnesia", "es": "amnesia"},
		{"en": "ancient power", "es": "forzantica"},
		{"en": "aqua jet", "es": "acquagetto"},
		{"en": "aqua ring", "es": "acquanello"},
		{"en": "aqua tail", "es": "idrondata"},
		{"en": "arm thrust", "es": "sberletese"},
		{"en": "aromatherapy", "es": "aromaterapia"},
		{"en": "aromatic mist", "es": "nebularoma"},
		{"en": "assist", "es": "assistente"},
		{"en": "assurance", "es": "garanzia"},
		{"en": "astonish", "es": "sgomento"},
		{"en": "attack order", "es": "comandourto"},
		{"en": "attract", "es": "attrazione"},
		{"en": "aura sphere", "es": "forzasfera"},
		{"en": "aurora beam", "es": "raggiaurora"},
		{"en": "autotomize", "es": "sganciapesi"},
		{"en": "avalanche", "es": "slavina"},
		{"en": "baby-doll eyes", "es": "occhioni teneri"},
		{"en": "barrage", "es": "attacco pioggia"},
		{"en": "barrier", "es": "barriera"},
		{"en": "baton pass", "es": "staffetta"},
		{"en": "beat up", "es": "picchiaduro"},
		{"en": "belch", "es": "rutto"},
		{"en": "belly drum", "es": "panciamburo"},
		{"en": "bestow", "es": "cediregalo"},
		{"en": "bide", "es": "pazienza"},
		{"en": "bind", "es": "legatutto"},
		{"en": "bite", "es": "morso"},
		{"en": "blast burn", "es": "incendio"},
		{"en": "blaze kick", "es": "calciardente"},
		{"en": "blizzard", "es": "bora"},
		{"en": "block", "es": "blocco"},
		{"en": "blue flare", "es": "fuocoblu"},
		{"en": "body slam", "es": "corposcontro"},
		{"en": "bolt strike", "es": "lucesiluro"},
		{"en": "bone club", "es": "ossoclava"},
		{"en": "bone rush", "es": "ossoraffica"},
		{"en": "bonemerang", "es": "ossomerang"},
		{"en": "boomburst", "es": "ondaboato"},
		{"en": "bounce", "es": "rimbalzo"},
		{"en": "brave bird", "es": "baldeali"},
		{"en": "brick break", "es": "breccia"},
		{"en": "brine", "es": "acquadisale"},
		{"en": "bubble beam", "es": "bollaraggio"},
		{"en": "bubble", "es": "bolla"},
		{"en": "bug bite", "es": "coleomorso"},
		{"en": "bug buzz", "es": "ronzio"},
		{"en": "bulk up", "es": "granfisico"},
		{"en": "bulldoze", "es": "battiterra"},
		{"en": "bullet punch", "es": "pugnoscarica"},
		{"en": "bullet seed", "es": "semitraglia"},
		{"en": "calm mind", "es": "calmamente"},
		{"en": "camouflage", "es": "cammuffamento"},
		{"en": "captivate", "es": "incanto"},
		{"en": "celebrate", "es": "auguri"},
		{"en": "charge beam", "es": "raggioscossa"},
		{"en": "charge", "es": "sottocarica"},
		{"en": "charm", "es": "fascino"},
		{"en": "chatter", "es": "schiamazzo"},
		{"en": "chip away", "es": "insidia"},
		{"en": "circle throw", "es": "ribaltiro"},
		{"en": "clamp", "es": "tenaglia"},
		{"en": "clear smog", "es": "pulifumo"},
		{"en": "close combat", "es": "zuffa"},
		{"en": "coil", "es": "arrotola"},
		{"en": "comet punch", "es": "cometapugno"},
		{"en": "confide", "es": "confidenza"},
		{"en": "confuse ray", "es": "stordiraggio"},
		{"en": "confusion", "es": "confusione"},
		{"en": "constrict", "es": "limitazione"},
		{"en": "conversion 2", "es": "conversione2"},
		{"en": "conversion", "es": "conversione"},
		{"en": "copycat", "es": "copione"},
		{"en": "cosmic power", "es": "cosmoforza"},
		{"en": "cotton guard", "es": "cotonscudo"},
		{"en": "cotton spore", "es": "cottonspora"},
		{"en": "counter", "es": "contrattacco"},
		{"en": "covet", "es": "supplica"},
		{"en": "crabhammer", "es": "martellata"},
		{"en": "crafty shield", "es": "truccodifesa"},
		{"en": "cross chop", "es": "incrocolpo"},
		{"en": "cross poison", "es": "velenocroce"},
		{"en": "crunch", "es": "sgranocchio"},
		{"en": "crush claw", "es": "tritartigli"},
		{"en": "crush grip", "es": "sbriciolmano"},
		{"en": "curse", "es": "maledizione"},
		{"en": "cut", "es": "taglio"},
		{"en": "dark pulse", "es": "neropulsar"},
		{"en": "dark void", "es": "vuototetro"},
		{"en": "dazzling gleam", "es": "magibrillio"},
		{"en": "defend order", "es": "comandoscudo"},
		{"en": "defense curl", "es": "ricciolscudo"},
		{"en": "defog", "es": "scacciabruma"},
		{"en": "destiny bond", "es": "destinobbl,"},
		{"en": "detect", "es": "individua"},
		{"en": "dig", "es": "fossa"},
		{"en": "disable", "es": "inibitore"},
		{"en": "disarming voice", "es": "incantavoce"},
		{"en": "discharge", "es": "scarica"},
		{"en": "dive", "es": "sub"},
		{"en": "dizzy punch", "es": "stordipugno"},
		{"en": "doom desire", "es": "obbliderio"},
		{"en": "double hit", "es": "doppiosmash"},
		{"en": "double kick", "es": "doppiocalcio"},
		{"en": "double slap", "es": "doppiasberla"},
		{"en": "double team", "es": "doppioteam"},
		{"en": "double-edge", "es": "sdoppiatore"},
		{"en": "draco meteor", "es": "dragobolide"},
		{"en": "dragon ascent", "es": "ascesa del drago"},
		{"en": "dragon breath", "es": "dragospiro"},
		{"en": "dragon claw", "es": "dragartigli"},
		{"en": "dragon dance", "es": "dragodanza"},
		{"en": "dragon pulse", "es": "dragopulsar"},
		{"en": "dragon rage", "es": "ira di drago"},
		{"en": "dragon rush", "es": "dragofuria"},
		{"en": "dragon tail", "es": "codadrago"},
		{"en": "drain punch", "es": "assorbipugno"},
		{"en": "draining kiss", "es": "assorbibacio"},
		{"en": "dream eater", "es": "mangiasogni"},
		{"en": "drill peck", "es": "perforbecco"},
		{"en": "drill run", "es": "giravvita"},
		{"en": "dual chop", "es": "doppiocolpo"},
		{"en": "dynamic punch", "es": "dinamipugno"},
		{"en": "earth power", "es": "geoforza"},
		{"en": "earthquake", "es": "terremoto"},
		{"en": "echoed voice", "es": "echeggiavoce"},
		{"en": "eerie impulse", "es": "elettromistero"},
		{"en": "egg bomb", "es": "uovobomba"},
		{"en": "electric terrain", "es": "campo elettrico"},
		{"en": "electrify", "es": "elettrocontagio"},
		{"en": "electro ball", "es": "energisfera"},
		{"en": "electroweb", "es": "elettrotela"},
		{"en": "embargo", "es": "divieto"},
		{"en": "ember", "es": "braciere"},
		{"en": "encore", "es": "ripeti"},
		{"en": "endeavor", "es": "rimonta"},
		{"en": "endure", "es": "resistenza"},
		{"en": "energy ball", "es": "energipalla"},
		{"en": "entrainment", "es": "saltamicizia"},
		{"en": "eruption", "es": "eruzione"},
		{"en": "explosion", "es": "esplosione"},
		{"en": "extrasensory", "es": "extrasenso"},
		{"en": "extreme speed", "es": "extrarapido"},
		{"en": "facade", "es": "facciata"},
		{"en": "fairy lock", "es": "blocco fatato"},
		{"en": "fairy wind", "es": "vento di fata"},
		{"en": "fake out", "es": "bruciapelo"},
		{"en": "fake tears", "es": "falselacrime"},
		{"en": "false swipe", "es": "falsofinale"},
		{"en": "feather dance", "es": "danzadipiume"},
		{"en": "feint attack", "es": "finta"},
		{"en": "feint", "es": "fintoattacco"},
		{"en": "fell stinger", "es": "pungiglione"},
		{"en": "fiery dance", "es": "voldifuoco"},
		{"en": "final gambit", "es": "azzardo"},
		{"en": "fire blast", "es": "fuocobomba"},
		{"en": "fire fang", "es": "rogodenti"},
		{"en": "fire pledge", "es": "fiammapatto"},
		{"en": "fire punch", "es": "fuocopugno"},
		{"en": "fire spin", "es": "turbofuoco"},
		{"en": "fissure", "es": "abisso"},
		{"en": "flail", "es": "flagello"},
		{"en": "flame burst", "es": "pirolancio"},
		{"en": "flame charge", "es": "nitrocarica"},
		{"en": "flame wheel", "es": "ruotafuoco"},
		{"en": "flamethrower", "es": "lanciafiamme"},
		{"en": "flare blitz", "es": "fuococarica"},
		{"en": "flash cannon", "es": "cannonflash"},
		{"en": "flash", "es": "flash"},
		{"en": "flatter", "es": "adulazione"},
		{"en": "fling", "es": "lancio"},
		{"en": "flower shield", "es": "fiordifesa"},
		{"en": "fly", "es": "volo"},
		{"en": "flying press", "es": "schiacciatuffo"},
		{"en": "focus blast", "es": "focalcolpo"},
		{"en": "focus energy", "es": "focalenergia"},
		{"en": "focus punch", "es": "centripugno"},
		{"en": "follow me", "es": "sonoqui"},
		{"en": "force palm", "es": "palmoforza"},
		{"en": "foresight", "es": "preveggenza"},
		{"en": "forest's curse", "es": "schiacciatuffo"},
		{"en": "foul play", "es": "ripicca"},
		{"en": "freeze shock", "es": "elettrogelo"},
		{"en": "freeze-dry", "es": "liofilizzazione"},
		{"en": "frenzy plant", "es": "radicalbero"},
		{"en": "frost breath", "es": "alitogelido"},
		{"en": "frustration", "es": "frustrazione"},
		{"en": "fury attack", "es": "furia"},
		{"en": "fury cutter", "es": "tagliofuria"},
		{"en": "fury swipes", "es": "sfuriate"},
		{"en": "fusion bolt", "es": "incrotuono"},
		{"en": "fusion flare", "es": "incrofiamma"},
		{"en": "future sight", "es": "divinazione"},
		{"en": "gastro acid", "es": "gastroacido"},
		{"en": "gear grind", "es": "ingracolpo"},
		{"en": "geomancy", "es": "geocontrollo"},
		{"en": "giga drain", "es": "gigassorbim,"},
		{"en": "giga impact", "es": "gigaimpatto"},
		{"en": "glaciate", "es": "gelamondo"},
		{"en": "glare", "es": "bagliore"},
		{"en": "grass knot", "es": "laccioerboso"},
		{"en": "grass pledge", "es": "erbapatto"},
		{"en": "grass whistle", "es": "meloderba"},
		{"en": "grassy terrain", "es": "campo erboso"},
		{"en": "gravity", "es": "gravità"},
		{"en": "growl", "es": "ruggito"},
		{"en": "growth", "es": "crescita"},
		{"en": "grudge", "es": "rancore"},
		{"en": "guard split", "es": "paridifesa"},
		{"en": "guard swap", "es": "barattoscudo"},
		{"en": "guillotine", "es": "ghigliottina"},
		{"en": "gunk shot", "es": "sporcolancio"},
		{"en": "gust", "es": "raffica"},
		{"en": "gyro ball", "es": "vortexpalla"},
		{"en": "hail", "es": "grandine"},
		{"en": "hammer arm", "es": "martelpugno"},
		{"en": "happy hour", "es": "cuccagna"},
		{"en": "harden", "es": "rafforzatore"},
		{"en": "haze", "es": "nube"},
		{"en": "head charge", "es": "ricciolata"},
		{"en": "head smash", "es": "zuccata"},
		{"en": "headbutt", "es": "bottintesta"},
		{"en": "heal bell", "es": "rintoccasana"},
		{"en": "heal block", "es": "anticura"},
		{"en": "heal order", "es": "comandocura"},
		{"en": "heal pulse", "es": "ondasana"},
		{"en": "healing wish", "es": "curardore"},
		{"en": "heart stamp", "es": "cuorestampo"},
		{"en": "heart swap", "es": "cuorbaratto"},
		{"en": "heat crash", "es": "marchiafuoco"},
		{"en": "heat wave", "es": "ondacalda"},
		{"en": "heavy slam", "es": "pesobomba"},
		{"en": "helping hand", "es": "altruismo"},
		{"en": "hex", "es": "sciagura"},
		{"en": "hidden power", "es": "introforza"},
		{"en": "high jump kick", "es": "calcinvolo"},
		{"en": "hold back", "es": "riguardo"},
		{"en": "hold hands", "es": "mano nella mano"},
		{"en": "hone claws", "es": "unghiaguzze"},
		{"en": "horn attack", "es": "incornata"},
		{"en": "horn drill", "es": "perforcorno"},
		{"en": "horn leech", "es": "legnicorno"},
		{"en": "howl", "es": "gridodilotta"},
		{"en": "hurricane", "es": "tifone"},
		{"en": "hydro cannon", "es": "idrocannone"},
		{"en": "hydro pump", "es": "idropompa"},
		{"en": "hyper beam", "es": "iper raggio"},
		{"en": "hyper fang", "es": "iperzanna"},
		{"en": "hyper voice", "es": "granvoce"},
		{"en": "hyperspace hole", "es": "forodimensionale"},
		{"en": "hyperspace fury", "es": "urtodimensionale"},
		{"en": "hypnosis", "es": "ipnosi"},
		{"en": "ice ball", "es": "palla gelo"},
		{"en": "ice beam", "es": "geloraggio"},
		{"en": "ice burn", "es": "vampagelida"},
		{"en": "ice fang", "es": "gelodenti"},
		{"en": "ice punch", "es": "gelopugno"},
		{"en": "ice shard", "es": "geloscheggia"},
		{"en": "icicle crash", "es": "scagliagelo"},
		{"en": "icicle spear", "es": "gelolancia"},
		{"en": "icy wind", "es": "ventogelato"},
		{"en": "imprison", "es": "esclusiva"},
		{"en": "incinerate", "es": "bruciatutto"},
		{"en": "inferno", "es": "marchiatura"},
		{"en": "infestation", "es": "assillo"},
		{"en": "ingrain", "es": "radicamento"},
		{"en": "ion deluge", "es": "pioggiaplasma"},
		{"en": "iron defense", "es": "ferroscudo"},
		{"en": "iron head", "es": "metaltestata"},
		{"en": "iron tail", "es": "codacciaio"},
		{"en": "judgment", "es": "giudizio"},
		{"en": "jump kick", "es": "calciosalto"},
		{"en": "karate chop", "es": "colpokarate"},
		{"en": "kinesis", "es": "cinèsi"},
		{"en": "king's shield", "es": "scudo reale"},
		{"en": "knock off", "es": "privazione"},
		{"en": "land's wrath", "es": "forza tellurica"},
		{"en": "last resort", "es": "ultimascelta"},
		{"en": "lava plume", "es": "lavasbuffo"},
		{"en": "leaf blade", "es": "fendifoglia"},
		{"en": "leaf storm", "es": "verdebufera"},
		{"en": "leaf tornado", "es": "vorticerba"},
		{"en": "leech life", "es": "sanguisuga"},
		{"en": "leech seed", "es": "parassiseme"},
		{"en": "leer", "es": "fulmisguardo"},
		{"en": "lick", "es": "leccata"},
		{"en": "light screen", "es": "schermoluce"},
		{"en": "lock-on", "es": "localizza"},
		{"en": "lovely kiss", "es": "demonbacio"},
		{"en": "low kick", "es": "colpo basso"},
		{"en": "low sweep", "es": "calciobasso"},
		{"en": "lucky chant", "es": "fortuncanto"},
		{"en": "lunar dance", "es": "lunardanza"},
		{"en": "luster purge", "es": "abbagliante"},
		{"en": "mach punch", "es": "pugnorapido"},
		{"en": "magic coat", "es": "magivelo"},
		{"en": "magic room", "es": "magicozona"},
		{"en": "magical leaf", "es": "fogliamagica"},
		{"en": "magma storm", "es": "magmaclisma"},
		{"en": "magnet bomb", "es": "bombagnete"},
		{"en": "magnet rise", "es": "magnetascesa"},
		{"en": "magnetic flux", "es": "controllo polare"},
		{"en": "magnitude", "es": "magnitudo"},
		{"en": "mat block", "es": "ribaltappeto"},
		{"en": "me first", "es": "precedenza"},
		{"en": "mean look", "es": "malosguardo"},
		{"en": "meditate", "es": "meditazione"},
		{"en": "mega drain", "es": "megassorbimento"},
		{"en": "mega kick", "es": "megacalcio"},
		{"en": "mega punch", "es": "megapugno"},
		{"en": "megahorn", "es": "megacorno"},
		{"en": "memento", "es": "memento"},
		{"en": "metal burst", "es": "metalscoppio"},
		{"en": "metal claw", "es": "ferrartigli"},
		{"en": "metal sound", "es": "ferrostrido"},
		{"en": "meteor mash", "es": "meteorpugno"},
		{"en": "metronome", "es": "metronomo"},
		{"en": "milk drink", "es": "buonlatte"},
		{"en": "mimic", "es": "mimica"},
		{"en": "mind reader", "es": "leggimente"},
		{"en": "minimize", "es": "minimizzato"},
		{"en": "miracle eye", "es": "miracolvista"},
		{"en": "mirror coat", "es": "specchiovelo"},
		{"en": "mirror move", "es": "speculmossa"},
		{"en": "mirror shot", "es": "cristalcolpo"},
		{"en": "mist ball", "es": "foschisfera"},
		{"en": "mist", "es": "nebbia"},
		{"en": "misty terrain", "es": "campo nebbioso"},
		{"en": "moonblast", "es": "forza lunare"},
		{"en": "moonlight", "es": "lucelunare"},
		{"en": "morning sun", "es": "mattindoro"},
		{"en": "mud bomb", "es": "pantanobomba"},
		{"en": "mud shot", "es": "colpodifango"},
		{"en": "mud sport", "es": "fangata"},
		{"en": "mud-slap", "es": "fangosberla"},
		{"en": "muddy water", "es": "fanghiglia"},
		{"en": "mystical fire", "es": "magifiamma"},
		{"en": "nasty plot", "es": "congiura"},
		{"en": "natural gift", "es": "dononaturale"},
		{"en": "nature power", "es": "naturforza"},
		{"en": "needle arm", "es": "pugnospine"},
		{"en": "night daze", "es": "urtoscuro"},
		{"en": "night shade", "es": "ombra notturna"},
		{"en": "night slash", "es": "nottesferza"},
		{"en": "nightmare", "es": "incubo"},
		{"en": "noble roar", "es": "urlo"},
		{"en": "nuzzle", "es": "elettrococcola"},
		{"en": "oblivion wing", "es": "ali del fato"},
		{"en": "octazooka", "es": "octazooka"},
		{"en": "odor sleuth", "es": "segugio"},
		{"en": "ominous wind", "es": "funestovento"},
		{"en": "origin pulse", "es": "primopulsar"},
		{"en": "outrage", "es": "oltraggio"},
		{"en": "overheat", "es": "vampata"},
		{"en": "pain split", "es": "malcomune"},
		{"en": "parabolic charge", "es": "caricaparabola"},
		{"en": "parting shot", "es": "monito"},
		{"en": "pay day", "es": "giornopaga"},
		{"en": "payback", "es": "rivincita"},
		{"en": "peck", "es": "beccata"},
		{"en": "perish song", "es": "ultimocanto"},
		{"en": "petal blizzard", "es": "fiortempesta"},
		{"en": "petal dance", "es": "petalodanza"},
		{"en": "phantom force", "es": "spettrotuffo"},
		{"en": "pin missile", "es": "missilspillo"},
		{"en": "play nice", "es": "simpatia"},
		{"en": "play rough", "es": "carineria"},
		{"en": "pluck", "es": "spennata"},
		{"en": "poison fang", "es": "velenodenti"},
		{"en": "poison gas", "es": "velenogas"},
		{"en": "poison jab", "es": "velenpuntura"},
		{"en": "poison powder", "es": "velenpolvere"},
		{"en": "poison sting", "es": "velenospina"},
		{"en": "poison tail", "es": "velenocoda"},
		{"en": "pound", "es": "botta"},
		{"en": "powder snow", "es": "polneve"},
		{"en": "powder", "es": "pulviscoppio"},
		{"en": "power gem", "es": "gemmoforza"},
		{"en": "power split", "es": "pariattacco"},
		{"en": "power swap", "es": "barattoforza"},
		{"en": "power trick", "es": "ingannoforza"},
		{"en": "power whip", "es": "vigorcolpo"},
		{"en": "power-up punch", "es": "crescipugno"},
		{"en": "precipice blades", "es": "spade telluriche"},
		{"en": "present", "es": "regalino"},
		{"en": "protect", "es": "protezione"},
		{"en": "psybeam", "es": "psicoraggio"},
		{"en": "psych up", "es": "psicamisù"},
		{"en": "psychic", "es": "psichico"},
		{"en": "psycho boost", "es": "psicoslancio"},
		{"en": "psycho cut", "es": "psicotaglio"},
		{"en": "psycho shift", "es": "psicotrasfer"},
		{"en": "psyshock", "es": "psicoshock"},
		{"en": "psystrike", "es": "psicobotta"},
		{"en": "psywave", "es": "psiconda"},
		{"en": "punishment", "es": "punizione"},
		{"en": "pursuit", "es": "inseguimento"},
		{"en": "quash", "es": "spintone"},
		{"en": "quick attack", "es": "attacco rapido"},
		{"en": "quick guard", "es": "anticipo"},
		{"en": "quiver dance", "es": "eledanza"},
		{"en": "rage powder", "es": "polverabbia"},
		{"en": "rage", "es": "ira"},
		{"en": "rain dance", "es": "pioggiadanza"},
		{"en": "rapid spin", "es": "rapigiro"},
		{"en": "razor leaf", "es": "foglielama"},
		{"en": "razor shell", "es": "conchilama"},
		{"en": "razor wind", "es": "ventagliente"},
		{"en": "recover", "es": "ripresa"},
		{"en": "recycle", "es": "riciclo"},
		{"en": "reflect type", "es": "riflettipo"},
		{"en": "reflect", "es": "riflesso"},
		{"en": "refresh", "es": "rinfrescata"},
		{"en": "relic song", "es": "cantoantico"},
		{"en": "rest", "es": "riposo"},
		{"en": "retaliate", "es": "nemesi"},
		{"en": "return", "es": "ritorno"},
		{"en": "revenge", "es": "vendetta"},
		{"en": "reversal", "es": "contropiede"},
		{"en": "roar of time", "es": "fragortempo"},
		{"en": "roar", "es": "boato"},
		{"en": "rock blast", "es": "cadutamassi"},
		{"en": "rock climb", "es": "scalaroccia"},
		{"en": "rock polish", "es": "lucidatura"},
		{"en": "rock slide", "es": "frana"},
		{"en": "rock smash", "es": "spaccaroccia"},
		{"en": "rock throw", "es": "sassata"},
		{"en": "rock tomb", "es": "rocciotomba"},
		{"en": "rock wrecker", "es": "devastomasso"},
		{"en": "role play", "es": "giocodiruolo"},
		{"en": "rolling kick", "es": "calciorullo"},
		{"en": "rollout", "es": "rotolamento"},
		{"en": "roost", "es": "trespolo"},
		{"en": "rototiller", "es": "aracampo"},
		{"en": "round", "es": "coro"},
		{"en": "sacred fire", "es": "magifuoco"},
		{"en": "sacred sword", "es": "spadasolenne"},
		{"en": "safeguard", "es": "salvaguardia"},
		{"en": "sand attack", "es": "turbosabbia"},
		{"en": "sand tomb", "es": "sabbiotomba"},
		{"en": "sandstorm", "es": "terrempesta"},
		{"en": "scald", "es": "idrovampata"},
		{"en": "scary face", "es": "visotruce"},
		{"en": "scratch", "es": "graffio"},
		{"en": "screech", "es": "stridio"},
		{"en": "searing shot", "es": "sparafuoco"},
		{"en": "secret power", "es": "forzasegreta"},
		{"en": "secret sword", "es": "spadamistica"},
		{"en": "seed bomb", "es": "semebomba"},
		{"en": "seed flare", "es": "infuriaseme"},
		{"en": "seismic toss", "es": "movimento sismico"},
		{"en": "self-destruct", "es": "autodistruzione"},
		{"en": "shadow ball", "es": "palla ombra"},
		{"en": "shadow claw", "es": "ombrartigli"},
		{"en": "shadow force", "es": "oscurotuffo"},
		{"en": "shadow punch", "es": "pugnodombra"},
		{"en": "shadow sneak", "es": "furtivombra"},
		{"en": "sharpen", "es": "affilatore"},
		{"en": "sheer cold", "es": "purogelo"},
		{"en": "shell smash", "es": "gettaguscio"},
		{"en": "shift gear", "es": "cambiomarcia"},
		{"en": "shock wave", "es": "ondashock"},
		{"en": "signal beam", "es": "segnoraggio"},
		{"en": "silver wind", "es": "ventargenteo"},
		{"en": "simple beam", "es": "ondisinvolta"},
		{"en": "sing", "es": "canto"},
		{"en": "sketch", "es": "schizzo"},
		{"en": "skill swap", "es": "baratto"},
		{"en": "skull bash", "es": "capocciata"},
		{"en": "sky attack", "es": "aeroattacco"},
		{"en": "sky drop", "es": "cadutalibera"},
		{"en": "sky uppercut", "es": "stramontante"},
		{"en": "slack off", "es": "pigro"},
		{"en": "slam", "es": "schianto"},
		{"en": "slash", "es": "lacerazione"},
		{"en": "sleep powder", "es": "sonnifero"},
		{"en": "sleep talk", "es": "sonnolalia"},
		{"en": "sludge bomb", "es": "fangobomba"},
		{"en": "sludge wave", "es": "fangonda"},
		{"en": "sludge", "es": "fango"},
		{"en": "smack down", "es": "abbattimento"},
		{"en": "smelling salts", "es": "maniereforti"},
		{"en": "smog", "es": "smog"},
		{"en": "smokescreen", "es": "muro di fumo"},
		{"en": "snarl", "es": "urlorabbia"},
		{"en": "snatch", "es": "scippo"},
		{"en": "snore", "es": "russare"},
		{"en": "soak", "es": "inondazione"},
		{"en": "soft-boiled", "es": "covauova"},
		{"en": "solar beam", "es": "solarraggio"},
		{"en": "sonic boom", "es": "sonicboom"},
		{"en": "spacial rend", "es": "fendispazio"},
		{"en": "spark", "es": "scintilla"},
		{"en": "spider web", "es": "ragnatela"},
		{"en": "spike cannon", "es": "sparalance"},
		{"en": "spikes", "es": "punte"},
		{"en": "spiky shield", "es": "agodifesa"},
		{"en": "spit up", "es": "sfoghenergia"},
		{"en": "spite", "es": "dispetto"},
		{"en": "splash", "es": "splash"},
		{"en": "spore", "es": "spora"},
		{"en": "stealth rock", "es": "levitoroccia"},
		{"en": "steamroller", "es": "rulloduro"},
		{"en": "steel wing", "es": "alacciaio"},
		{"en": "sticky web", "es": "rete vischiosa"},
		{"en": "stockpile", "es": "accumulo"},
		{"en": "stomp", "es": "pestone"},
		{"en": "stone edge", "es": "pietrataglio"},
		{"en": "stored power", "es": "veicolaforza"},
		{"en": "storm throw", "es": "tempestretta"},
		{"en": "strength", "es": "forza"},
		{"en": "string shot", "es": "millebave"},
		{"en": "struggle bug", "es": "entomoblocco"},
		{"en": "struggle", "es": "scontro"},
		{"en": "stun spore", "es": "paralizzante"},
		{"en": "submission", "es": "sottomissione"},
		{"en": "substitute", "es": "sostituto"},
		{"en": "sucker punch", "es": "sbigoattacco"},
		{"en": "sunny day", "es": "giornodisole"},
		{"en": "super fang", "es": "superzanna"},
		{"en": "superpower", "es": "troppoforte"},
		{"en": "supersonic", "es": "supersuono"},
		{"en": "surf", "es": "surf"},
		{"en": "swagger", "es": "bullo"},
		{"en": "swallow", "es": "introenergia"},
		{"en": "sweet kiss", "es": "dolcebacio"},
		{"en": "sweet scent", "es": "profumino"},
		{"en": "swift", "es": "comete"},
		{"en": "switcheroo", "es": "rapidscambio"},
		{"en": "swords dance", "es": "danzaspada"},
		{"en": "synchronoise", "es": "sincrumore"},
		{"en": "synthesis", "es": "sintesi"},
		{"en": "tackle", "es": "azione"},
		{"en": "tail glow", "es": "codadiluce"},
		{"en": "tail slap", "es": "spazzasberla"},
		{"en": "tail whip", "es": "colpocoda"},
		{"en": "tailwind", "es": "ventoincoda"},
		{"en": "take down", "es": "riduttore"},
		{"en": "taunt", "es": "provocazione"},
		{"en": "techno blast", "es": "tecnobotto"},
		{"en": "teeter dance", "es": "strampadanza"},
		{"en": "telekinesis", "es": "telecinesi"},
		{"en": "teleport", "es": "teletrasporto"},
		{"en": "thief", "es": "furto"},
		{"en": "thrash", "es": "colpo"},
		{"en": "thunder fang", "es": "fulmindenti"},
		{"en": "thunder punch", "es": "tuonopugno"},
		{"en": "thunder shock", "es": "tuonoshock"},
		{"en": "thunder wave", "es": "tuononda"},
		{"en": "thunder", "es": "tuono"},
		{"en": "thunderbolt", "es": "fulmine"},
		{"en": "tickle", "es": "solletico"},
		{"en": "topsy-turvy", "es": "sottosopra"},
		{"en": "torment", "es": "attaccalite"},
		{"en": "toxic spikes", "es": "fielepunte"},
		{"en": "toxic", "es": "tossina"},
		{"en": "transform", "es": "trasformazione"},
		{"en": "tri attack", "es": "tripletta"},
		{"en": "trick room", "es": "distortozona"},
		{"en": "trick", "es": "raggiro"},
		{"en": "trick-or-treat", "es": "halloween"},
		{"en": "triple kick", "es": "triplocalcio"},
		{"en": "trump card", "es": "asso"},
		{"en": "twineedle", "es": "doppio ago"},
		{"en": "twister", "es": "tornado"},
		{"en": "u-turn", "es": "retromarcia"},
		{"en": "uproar", "es": "baraonda"},
		{"en": "v-create", "es": "generatore v"},
		{"en": "vacuum wave", "es": "vuotonda"},
		{"en": "venom drench", "es": "velenotrappola"},
		{"en": "venoshock", "es": "velenoshock"},
		{"en": "vice grip", "es": "presa"},
		{"en": "vine whip", "es": "frustata"},
		{"en": "vital throw", "es": "vitaltiro"},
		{"en": "volt switch", "es": "invertivolt"},
		{"en": "volt tackle", "es": "locomovolt"},
		{"en": "wake-up slap", "es": "svegliopacca"},
		{"en": "water gun", "es": "pistolacqua"},
		{"en": "water pledge", "es": "acquapatto"},
		{"en": "water pulse", "es": "idropulsar"},
		{"en": "water shuriken", "es": "acqualame"},
		{"en": "water sport", "es": "docciascudo"},
		{"en": "water spout", "es": "zampillo"},
		{"en": "waterfall", "es": "cascata"},
		{"en": "weather ball", "es": "palla clima"},
		{"en": "whirlpool", "es": "mulinello"},
		{"en": "whirlwind", "es": "turbine"},
		{"en": "wide guard", "es": "bodyguard"},
		{"en": "wild charge", "es": "sprizzalampo"},
		{"en": "will-o-wisp", "es": "fuocofatuo"},
		{"en": "wing attack", "es": "attacco d'ala"},
		{"en": "wish", "es": "desiderio"},
		{"en": "withdraw", "es": "ritirata"},
		{"en": "wonder room", "es": "mirabilzona"},
		{"en": "wood hammer", "es": "mazzuolegno"},
		{"en": "work up", "es": "cuordileone"},
		{"en": "worry seed", "es": "affannoseme"},
		{"en": "wrap", "es": "avvolgibotta"},
		{"en": "wring out", "es": "strizzata"},
		{"en": "x-scissor", "es": "forbice x"},
		{"en": "yawn", "es": "sbadiglio"},
		{"en": "zap cannon", "es": "falcecannone"},
		{"en": "zen headbutt", "es": "cozzata zen"}
	],
	"item": [
		{"en": "absorb bulb", "es": "bulbo"},
		{"en": "adamant orb", "es": "adamasfera"},
		{"en": "air balloon", "es": "palloncino"},
		{"en": "amulet coin", "es": "monetamuleto"},
		{"en": "assault vest", "es": "corpetto assalto"},
		{"en": "berry juice", "es": " succo di bacca"},
		{"en": "berserk gene", "es": "gene furioso"},
		{"en": "big root", "es": "granradice"},
		{"en": "binding band", "es": "legafascia"},
		{"en": "black belt", "es": "cinturanera"},
		{"en": "black glasses", "es": "occhialineri"},
		{"en": "black sludge", "es": "fangopece"},
		{"en": "blue scarf", "es": "fascia blu"},
		{"en": "bright powder", "es": "luminpolvere"},
		{"en": "bug gem", "es": "bijoucoleot,"},
		{"en": "burn drive", "es": "piromodulo"},
		{"en": "cell battery", "es": "ricaripila"},
		{"en": "charcoal", "es": "carbonella"},
		{"en": "chill drive", "es": "gelomodulo"},
		{"en": "choice band", "es": "bendascelta"},
		{"en": "choice scarf", "es": "stolascelta"},
		{"en": "choice specs", "es": "lentiscelta"},
		{"en": "cleanse tag", "es": "velopuro"},
		{"en": "damp rock", "es": "rocciaumida"},
		{"en": "dark gem", "es": "bijoubuio"},
		{"en": "deep sea scale", "es": "squamabissi"},
		{"en": "deep sea tooth", "es": "denteabissi"},
		{"en": "destiny knot", "es": "destincomune"},
		{"en": "douse drive", "es": "idromodulo"},
		{"en": "draco plate", "es": "lastradrakon"},
		{"en": "dragon fang", "es": "dentedidrago"},
		{"en": "dragon gem", "es": "bijoudrago"},
		{"en": "dragon scale", "es": "squama drago"},
		{"en": "dread plate", "es": "lastratimore"},
		{"en": "dubious disc", "es": "dubbiodisco"},
		{"en": "earth plate", "es": "lastrageo"},
		{"en": "eject button", "es": "pulsantefuga"},
		{"en": "electirizer", "es": "elettritore"},
		{"en": "electric gem", "es": "bijouelettro"},
		{"en": "everstone", "es": "pietrastante"},
		{"en": "eviolite", "es": "evolcondensa"},
		{"en": "exp, share", "es": "condividi esp,*"},
		{"en": "expert belt", "es": "abilcintura"},
		{"en": "fighting gem", "es": "bijoulotta"},
		{"en": "fire gem", "es": "bijoufuoco"},
		{"en": "fist plate", "es": "lastrapugno"},
		{"en": "flame orb", "es": "fiammosfera"},
		{"en": "flame plate", "es": "lastrarogo"},
		{"en": "float stone", "es": "pietralieve"},
		{"en": "flying gem", "es": "bijouvolante"},
		{"en": "focus band", "es": "bandana"},
		{"en": "focus sash", "es": "focalnastro"},
		{"en": "fresh water", "es": "acqua fresca"},
		{"en": "full incense", "es": "gonfioaroma"},
		{"en": "ghost gem", "es": "bijouspettro"},
		{"en": "grass gem", "es": "bijouerba"},
		{"en": "green scarf", "es": "fascia verde"},
		{"en": "grip claw", "es": "presartigli"},
		{"en": "griseous orb", "es": "grigiosfera"},
		{"en": "ground gem", "es": "bijouterra"},
		{"en": "hard stone", "es": "pietradura"},
		{"en": "heat rock", "es": "rocciacalda"},
		{"en": "ice gem", "es": "bijoughiac,"},
		{"en": "icicle plate", "es": "lastragelo"},
		{"en": "icy rock", "es": "rocciafredda"},
		{"en": "insect plate", "es": "lastrabaco"},
		{"en": "iron ball", "es": "ferropalla"},
		{"en": "iron plate", "es": "lastraferro"},
		{"en": "king's rock", "es": "roccia di re"},
		{"en": "lagging tail", "es": "rallentocoda"},
		{"en": "lax incense", "es": "distraroma"},
		{"en": "leftovers", "es": "avanzi"},
		{"en": "lemonade", "es": "lemonsucco"},
		{"en": "life orb", "es": "assorbisfera"},
		{"en": "light ball", "es": "elettropalla"},
		{"en": "light clay", "es": "creta luce"},
		{"en": "luck incense", "es": "fortunaroma"},
		{"en": "lucky egg", "es": "fortunuovo"},
		{"en": "lucky punch", "es": "fortunpugno"},
		{"en": "lustrous orb", "es": "splendisfera"},
		{"en": "macho brace", "es": "crescicappa"},
		{"en": "magmarizer", "es": "magmatore"},
		{"en": "magnet", "es": "calamita"},
		{"en": "meadow plate", "es": "lastraprato"},
		{"en": "mental herb", "es": "mentalerba"},
		{"en": "metal coat", "es": "metalcoperta"},
		{"en": "metal powder", "es": "metalpolvere"},
		{"en": "metronome", "es": "plessimetro"},
		{"en": "mind plate", "es": "lastramente"},
		{"en": "miracle seed", "es": "miracolseme"},
		{"en": "moomoo milk", "es": "latte mumu"},
		{"en": "muscle band", "es": "muscolbanda"},
		{"en": "mystic water", "es": "acquamagica"},
		{"en": "never-melt ice", "es": "gelomai"},
		{"en": "normal gem", "es": "bijounormale"},
		{"en": "odd incense", "es": "bizzoaroma"},
		{"en": "pink bow", "es": "fiocco rosa"},
		{"en": "pink scarf", "es": "fascia rosa"},
		{"en": "poison barb", "es": "velenago"},
		{"en": "poison gem", "es": "bijouveleno"},
		{"en": "polkadot bow", "es": "fiocco pois"},
		{"en": "power anklet", "es": "vigorgliera"},
		{"en": "power band", "es": "vigorbanda"},
		{"en": "power belt", "es": "vigorfascia"},
		{"en": "power bracer", "es": "vigorcerchio"},
		{"en": "power herb", "es": "vigorerba"},
		{"en": "power lens", "es": "vigorlente"},
		{"en": "power weight", "es": "vigorpeso"},
		{"en": "prism scale", "es": "squama bella"},
		{"en": "protector", "es": "copertura"},
		{"en": "psychic gem", "es": "bijoupsico"},
		{"en": "pure incense", "es": "puroaroma"},
		{"en": "quick claw", "es": "rapidartigli"},
		{"en": "quick powder", "es": "velopolvere"},
		{"en": "razor claw", "es": "affilartigli"},
		{"en": "razor fang", "es": "affilodente"},
		{"en": "reaper cloth", "es": "terrorpanno"},
		{"en": "red card", "es": "cartelrosso"},
		{"en": "red scarf", "es": "fascia rossa"},
		{"en": "ring target", "es": "facilsaglio"},
		{"en": "rock gem", "es": "bijouroccia"},
		{"en": "rock incense", "es": "roccioaroma"},
		{"en": "rocky helmet", "es": "bitorzolelmo"},
		{"en": "rose incense", "es": "rosaroma"},
		{"en": "safety goggles", "es": "visierantisabbia"},
		{"en": "scope lens", "es": "mirino"},
		{"en": "sea incense", "es": "marearoma"},
		{"en": "sharp beak", "es": "beccaffilato"},
		{"en": "shed shell", "es": "disfoguscio"},
		{"en": "shell bell", "es": "conchinella"},
		{"en": "shock drive", "es": "voltmodulo"},
		{"en": "silk scarf", "es": "sciarpaseta"},
		{"en": "silver powder", "es": "argenpolvere"},
		{"en": "sky plate", "es": "lastracielo"},
		{"en": "smoke ball", "es": "palla fumo"},
		{"en": "smooth rock", "es": "roccialiscia"},
		{"en": "snowball", "es": "palla di neve"},
		{"en": "soda pop", "es": "gassosa"},
		{"en": "soft sand", "es": "sabbiasoffice"},
		{"en": "soothe bell", "es": "calmanella"},
		{"en": "soul dew", "es": "cuorugiada"},
		{"en": "spell tag", "es": "spettrotarga"},
		{"en": "splash plate", "es": "lastraidro"},
		{"en": "spooky plate", "es": "lastratetra"},
		{"en": "steel gem", "es": "bijouacciaio"},
		{"en": "stick", "es": "gambo"},
		{"en": "sticky barb", "es": "vischiopunta"},
		{"en": "stone plate", "es": "lastrapietra"},
		{"en": "tea", "es": "tè"},
		{"en": "thick club", "es": "ossospesso"},
		{"en": "toxic orb", "es": "tossicsfera"},
		{"en": "toxic plate", "es": "lastrafiele"},
		{"en": "twisted spoon", "es": "cucchiaiotorto"},
		{"en": "up-grade", "es": "upgrade"},
		{"en": "water gem", "es": "bijouacqua"},
		{"en": "wave incense", "es": "ondaroma"},
		{"en": "weakness policy", "es": "vulneropolizza"},
		{"en": "whipped dream", "es": "dolcespuma"},
		{"en": "white herb", "es": "erbachiara"},
		{"en": "wide lens", "es": "grandelente"},
		{"en": "wise glasses", "es": "saviocchiali"},
		{"en": "yellow scarf", "es": "fascia gialla"},
		{"en": "zap plate", "es": "lastrasaetta"},
		{"en": "zoom lens", "es": "zoomlente"}
	],
	"berry": [
		{"en": "aguav berry", "es": "Baya Guaya"},
		{"en": "apicot berry", "es": "Baya Aricoc"},
		{"en": "aspear berry", "es": "Baya Perasi"},
		{"en": "babiri berry", "es": "Baya Baribá"},
		{"en": "belue berry", "es": "Baya Andano"},
		{"en": "bluk berry", "es": "Baya Oram"},
		{"en": "charti berry", "es": "Baya Alcho"},
		{"en": "cheri berry", "es": "Baya Zreza"},
		{"en": "chesto berry", "es": "Baya Atania"},
		{"en": "chilan berry", "es": "Baya Chilan"},
		{"en": "chople berry", "es": "Baya Pomaro"},
		{"en": "coba berry", "es": "Baya Kouba"},
		{"en": "colbur berry", "es": "Baya Dillo"},
		{"en": "cornn berry", "es": "Baya Mais"},
		{"en": "custap berry", "es": "Baya Chiri"},
		{"en": "durin berry", "es": "Baya Rudion"},
		{"en": "enigma berry", "es": "Baya Enigma"},
		{"en": "figy berry", "es": "Baya Higog"},
		{"en": "ganlon berry", "es": "Baya Gonlan"},
		{"en": "grepa berry", "es": "Baya Uvav"},
		{"en": "haban berry", "es": "Baya Anjiro"},
		{"en": "hondew berry", "es": "Baya Meluce"},
		{"en": "iapapa berry", "es": "Baya Pabaya"},
		{"en": "jaboca berry", "es": "Baya Jaboca"},
		{"en": "kasib berry", "es": "Baya Drasi"},
		{"en": "kebia berry", "es": "Baya Kebia"},
		{"en": "kee berry", "es": "Baya Biglia"},
		{"en": "kelpsy berry", "es": "Baya Algama"},
		{"en": "lansat berry", "es": "Baya Zonlan"},
		{"en": "leppa berry", "es": "Baya Zanama"},
		{"en": "liechi berry", "es": "Baya Lichi"},
		{"en": "lum berry", "es": "Baya Ziuela"},
		{"en": "mago berry", "es": "Baya Ango"},
		{"en": "magost berry", "es": "Baya Aostan"},
		{"en": "maranga berry", "es": "Baya Maranga"},
		{"en": "micle berry", "es": "Baya Lagro"},
		{"en": "nanab berry", "es": "Baya Latano"},
		{"en": "nomel berry", "es": "Baya Monli"},
		{"en": "occa berry", "es": "Baya Caoca"},
		{"en": "oran berry", "es": "Baya Aranka"},
		{"en": "pamtre berry", "es": "Baya Plama"},
		{"en": "passho berry", "es": "Baya Basio"},
		{"en": "payapa berry", "es": "Baya Payapa"},
		{"en": "pecha berry", "es": "Baya Meloc"},
		{"en": "persim berry", "es": "Baya Caquic"},
		{"en": "petaya berry", "es": "Baya Yapati"},
		{"en": "pinap berry", "es": "Baya Pinia"},
		{"en": "pomeg berry", "es": "Baya Grana"},
		{"en": "qualot berry", "es": "Baya Ispero"},
		{"en": "rabuta berry", "es": "Baya Rautan"},
		{"en": "rawst berry", "es": "Baya Safre"},
		{"en": "razz berry", "es": "Baya Frambu"},
		{"en": "rindo berry", "es": "Baya Tamar"},
		{"en": "roseli berry", "es": "Baya Hibis"},
		{"en": "rowap berry", "es": "Baya Magua"},
		{"en": "salac berry", "es": "Baya Aslac"},
		{"en": "shuca berry", "es": "Baya Acardo"},
		{"en": "sitrus berry", "es": "Baya Zidra"},
		{"en": "spelon berry", "es": "Baya Wikano"},
		{"en": "starf berry", "es": "Baya Arabol"},
		{"en": "tamato berry", "es": "Baya Tamate"},
		{"en": "tanga berry", "es": "Baya Yecana"},
		{"en": "wacan berry", "es": "Baya Gualot"},
		{"en": "watmel berry", "es": "Baya Sambia"},
		{"en": "wepear berry", "es": "Baya Peragu"},
		{"en": "wiki berry", "es": "Baya Wiki"},
		{"en": "yache berry", "es": "Baya Rimoya"}
	],
	"megastone" : [
		{"en": "abomasite", "es": "abomasnowite"},
		{"en": "absolite", "es": "absolite"},
		{"en": "aerodactylite", "es": "aerodactylite"},
		{"en": "aggronite", "es": "aggronite"},
		{"en": "alakazite", "es": "alakazamite"},
		{"en": "ampharosite", "es": "ampharosite"},
		{"en": "banettite", "es": "banettite"},
		{"en": "blastoisinite", "es": "blastoisite"},
		{"en": "blazikenite", "es": "blazikenite"},
		{"en": "charizardite x", "es": "charizardite x"},
		{"en": "charizardite y", "es": "charizardite y"},
		{"en": "diancite", "es": "diancite"},
		{"en": "garchompite", "es": "garchompite"},
		{"en": "gardevoirite", "es": "gardevoirite"},
		{"en": "gengarite", "es": "gengarite"},
		{"en": "glalitite", "es": "glalite"},
		{"en": "gyaradosite", "es": "gyaradosite"},
		{"en": "heracronite", "es": "heracrossite"},
		{"en": "houndoominite", "es": "houndoomite"},
		{"en": "kangaskhanite", "es": "kangaskhanite"},
		{"en": "latiasite", "es": "latiasite"},
		{"en": "latiosite", "es": "latiosite"},
		{"en": "lucarionite", "es": "lucarite"},
		{"en": "manectite", "es": "manectricite"},
		{"en": "mawilite", "es": "mawilite"},
		{"en": "medichamite", "es": "medichamite"},
		{"en": "metagrossite", "es": "metagrossite"},
		{"en": "mewtwonite x", "es": "mewtwoite x"},
		{"en": "mewtwonite y", "es": "mewtwoite y"},
		{"en": "pinsirite", "es": "pinsirite"},
		{"en": "sceptilite", "es": "sceptilite"},
		{"en": "scizorite", "es": "scizorite"},
		{"en": "steelixite", "es": "steelixite"},
		{"en": "swampertite", "es": "swampertite"},
		{"en": "tyranitarite", "es": "tyranitarite"},
		{"en": "venusaurite", "es": "venusaurite"}
	],
	"nature": [
                {"en": "adamant", "es": "Firme"},
                {"en": "bashful", "es": "Tímida"},
                {"en": "bold", "es": "Osada"},
                {"en": "brave", "es": "Audaz"},
                {"en": "calm", "es": "Serena"},
                {"en": "careful", "es": "Cauta"},
                {"en": "docile", "es": "Dócil"},
                {"en": "gentle", "es": "Amable"},
                {"en": "hardy", "es": "Fuerte"},
                {"en": "hasty", "es": "Activa"},
                {"en": "impish", "es": "Agitada"},
                {"en": "jolly", "es": "Alegre"},
                {"en": "lax", "es": "Floja"},
                {"en": "lonely", "es": "Huraña"},
                {"en": "mild", "es": "Afable"},
                {"en": "modest", "es": "Modesta"},
                {"en": "naive", "es": "Ingenua"},
                {"en": "naughty", "es": "Pícara"},
                {"en": "quiet", "es": "Mansa"},
                {"en": "quirky", "es": "Rara"},
                {"en": "rash", "es": "Alocada"},
                {"en": "relaxed", "es": "Plácida"},
                {"en": "sassy", "es": "Grosera"},
                {"en": "serious", "es": "Seria"},
                {"en": "timid", "es": "Miedosa"}
	]
};
